#!/usr/bin/env python3
"""Pull the authored tables out of the C source and write them as GDScript.

The C game is the reference. Its classes, spells and monster rosters are
hand-written tables, and copying them by hand into the port is how the two
would drift apart -- so they are read from ../src every time this runs, and
the generated files say so at the top.

    python3 tools/gen_data.py        (from AetherDescent/godot)

Writes scripts/data/classes_data.gd, spells_data.gd and monsters_data.gd.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GODOT = os.path.dirname(HERE)
SRC = os.path.join(os.path.dirname(GODOT), "src")
OUT = os.path.join(GODOT, "scripts", "data")

ATTRS = [
    "MIGHT", "BRAWN", "AGILITY", "REFLEXES", "PRECISION",
    "GRIT", "FORTITUDE", "STAMINA", "BALANCE", "VISION",
    "HEARING", "INTELLECT", "CUNNING", "MEMORY", "RESOLVE",
    "INSTINCT", "CHARM", "GUILE", "PRESENCE", "EMPATHY",
    "TECH_WIT", "CRAFTING", "CHEMISTRY", "SCRIBING", "AETHER_SENSE",
    "CONDUIT", "RESONANCE", "WARDING", "FORTUNE", "JINX",
]
ARCHETYPES = ["VANGUARD", "SKIRMISHER", "MARKSMAN", "ARCANIST",
              "ARTIFICER", "SURVIVOR", "ENVOY"]
EFFECTS = [
    "DAMAGE", "DAMAGE_NOVA", "SCORCH", "BUFF_ATK", "HEAL_SELF", "WARD_SHIELD",
    "BARRIER", "PURGE", "BLINK", "REVEAL", "BRIDGE", "STUN", "SLOW", "UNBIND",
    "LIFE_DRAIN", "CURSE", "DOT_BURN", "CHAIN", "PARTY_HEAL", "HASTE",
    "REFLECT", "SENSE_LIFE", "MASS_SLOW",
]
SPELL_ARCHS = ["BALANCED", "OVERCHARGED", "EFFICIENT", "HEAVY", "FRUGAL"]
SCHOOL_TABLES = ["CONDUIT_CURATED", "RESONANCE_CURATED", "WARDING_CURATED",
                 "AETHER_SENSE_CURATED", "SCRIBING_CURATED", "JINX_CURATED"]
FAMILIES = {"CP_MON_VERMIN": 0, "CP_MON_CLOCKWORK": 1, "CP_MON_RUINS": 2,
            "CP_MON_OUTRIDER": 3, "CP_MON_ABYSSAL": 4}


def read(name):
    with open(os.path.join(SRC, name), encoding="utf-8") as f:
        return f.read()


def gd_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def header(what):
    return ("# GENERATED by tools/gen_data.py from ../src/%s -- do not edit by hand.\n"
            "# Re-run the generator after changing the C tables.\n" % what)


def gen_classes():
    text = read("classdata.c")
    overrides = {}
    for m in re.finditer(r"static const AttrOverride (OV\d+)\[\] = \{(.*?)OV_END \};", text):
        pairs = re.findall(r"\{ATTR_(\w+),(\d+)\}", m.group(2))
        overrides[m.group(1)] = [(ATTRS.index(a), int(v)) for a, v in pairs]
    rows = re.findall(
        r'\{ "((?:[^"\\]|\\.)*)", "((?:[^"\\]|\\.)*)", (OV\d+), "((?:[^"\\]|\\.)*)", '
        r'"((?:[^"\\]|\\.)*)", ARCH_(\w+) \}', text)
    if len(rows) != 100:
        sys.exit("expected 100 classes in classdata.c, found %d" % len(rows))
    out = [header("classdata.c"), "class_name ClassesData\n\n",
           "## One entry per class, in CLASS_TABLE order. `attrs` lists only the\n"
           "## overrides; every attribute not named is 3, the average person.\n",
           "const CLASSES := [\n"]
    for name, tag, ov, weapon, armor, arch in rows:
        attrs = ", ".join("[%d, %d]" % p for p in overrides[ov])
        out.append("\t{\"name\": %s, \"tagline\": %s, \"attrs\": [%s],\n"
                   "\t\t\"weapon\": %s, \"armor\": %s, \"archetype\": %d},\n"
                   % (gd_str(name), gd_str(tag), attrs, gd_str(weapon), gd_str(armor),
                      ARCHETYPES.index(arch)))
    out.append("]\n")
    return "".join(out)


def gen_spells():
    text = read("spells.c")
    out = [header("spells.c"), "class_name SpellsData\n\n",
           "## The curated pool: six schools, thirty spells each, in pool order.\n"
           "## [name, level, effect, archetype] -- stats come from the level tables\n"
           "## in spells.gd, exactly as make_template() builds them in C.\n",
           "const CURATED := [\n"]
    for table in SCHOOL_TABLES:
        m = re.search(r"static const CuratedSpell %s\[CURATED_PER_SCHOOL\] = \{(.*?)\n\};" % table,
                      text, re.S)
        if not m:
            sys.exit("could not find %s in spells.c" % table)
        rows = re.findall(r'\{"((?:[^"\\]|\\.)*)",\s*(\d),\s*EFFECT_(\w+),\s*ARCH_(\w+)\}', m.group(1))
        if len(rows) != 30:
            sys.exit("%s: expected 30 spells, found %d" % (table, len(rows)))
        out.append("\t[\n")
        for name, level, eff, arch in rows:
            out.append("\t\t[%s, %s, %d, %d],\n" % (gd_str(name), level, EFFECTS.index(eff),
                                                 SPELL_ARCHS.index(arch)))
        out.append("\t],\n")
    out.append("]\n")
    return "".join(out)


def gen_monsters():
    text = read("monsters.c")
    out = [header("monsters.c"), "class_name MonstersData\n\n",
           "## The hand-authored roster per depth tier:\n"
           "## [name, glyph, family, hp, atk, def, xp, gold]\n",
           "const CURATED := [\n"]
    for t in range(1, 6):
        m = re.search(r"static const MonsterTemplate TIER%d\[\] = \{(.*?)\n\};" % t, text, re.S)
        rows = re.findall(r"\{\s*\"([^\"]+)\",\s*'(.)',\s*(CP_MON_\w+),\s*(\d+),\s*(\d+),\s*(\d+),"
                          r"\s*(\d+),\s*(\d+)\}", m.group(1))
        out.append("\t[\n")
        for name, glyph, cp, hp, atk, df, xp, gold in rows:
            out.append("\t\t[%s, %s, %d, %s, %s, %s, %s, %s],\n"
                       % (gd_str(name), gd_str(glyph), FAMILIES[cp], hp, atk, df, xp, gold))
        out.append("\t],\n")
    out.append("]\n\n")
    for kind in ("PREFIXES", "NOUNS"):
        out.append("const %s := [\n" % kind)
        for t in range(1, 6):
            m = re.search(r"static const char \*T%d_%s\[\] = \{(.*?)\};" % (t, kind), text, re.S)
            words = re.findall(r'"([^"]+)"', m.group(1))
            out.append("\t[%s],\n" % ", ".join(gd_str(w) for w in words))
        out.append("]\n\n")
    m = re.search(r"static const double TIER_BASE\[5\]\[5\] = \{(.*?)\n\};", text, re.S)
    rows = re.findall(r"\{\s*([\d.]+),\s*([\d.]+),\s*([\d.]+),\s*([\d.]+),\s*([\d.]+)\s*\}", m.group(1))
    out.append("## Average baseline per tier for the generated variants: hp, atk, def, xp, gold\n")
    out.append("const TIER_BASE := [\n")
    for r in rows:
        out.append("\t[%s],\n" % ", ".join(str(float(v)) for v in r))
    out.append("]\n\n")
    m = re.search(r"static const Archetype ARCHETYPES\[\] = \{(.*?)\n\};", text, re.S)
    rows = re.findall(r"\{([\d.]+),\s*([\d.]+),\s*([\d.]+),\s*([\d.]+),\s*([\d.]+)\}", m.group(1))
    out.append("## Variant archetypes (Grunt, Brute, Skirmisher, Ambusher, Tank, Glass Cannon,\n"
               "## Veteran, Swarmling): multipliers on hp, atk, def, xp, gold\n")
    out.append("const ARCHETYPES := [\n")
    for r in rows:
        out.append("\t[%s],\n" % ", ".join(r))
    out.append("]\n")
    return "".join(out)


def main():
    os.makedirs(OUT, exist_ok=True)
    for fname, fn in (("classes_data.gd", gen_classes), ("spells_data.gd", gen_spells),
                      ("monsters_data.gd", gen_monsters)):
        path = os.path.join(OUT, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(fn())
        print("wrote", os.path.relpath(path, GODOT))


if __name__ == "__main__":
    main()
