# GENERATED by tools/gen_art.py -- the index into the generated textures.
class_name ArtLayout

const TILE := 32
const TILE_KINDS := ["floor0", "floor1", "floor2", "floor3", "grown0", "grown1", "grass0", "grass1", "flowers", "thicket0", "thicket1", "face0", "face1", "face2", "top0", "top1", "water0", "water1", "lava0", "lava1", "stairs_down", "stairs_up", "bridge", "miasma", "portal", "locked_door", "sealed_door", "lever", "crystal", "bloodpool", "prism_red", "prism_blue", "prism_green", "snare", "ore", "rubble"]
const TOWN_KINDS := ["cobble0", "cobble1", "cobble2", "cobble3", "roof_red", "roof_teal", "roof_slate", "house_wall", "door_general", "door_armory", "door_apothecary", "door_arcanist", "door_inn", "door_tavern", "door_junkyard", "door_gladiator", "door_bank", "door_races", "door_kitchen", "door_blackmarket", "door_oracle", "door_altar", "door_bazaar", "fountain", "quest_board", "grass", "flowers", "temple", "planter"]
const TOWN_ROW := 5
const HERO_CELL := Vector2i(48, 60)
const HERO_FEET_Y := 57
const HERO_LOOKS := 14
const HERO_FACINGS := ["down", "left", "right", "up"]
const HERO_FRAMES := ["walk0", "walk1", "walk2", "walk3", "atk0", "atk1", "atk2", "cast"]
const PORTRAIT := 64
const EXPRESSIONS := ["neutral", "happy", "angry", "hurt"]
const MON_CELL := 48
const BOSS_CELL := 72
const MON_KINDS := ["rat", "serpent", "tribal", "wisp", "automaton", "wraith", "golem", "hound", "horror"]
const MON_FAMILIES := ["jungle", "vermin", "clockwork", "ruins", "outrider", "abyssal", "spirit", "flame", "boss"]
const PROP_KINDS := ["gold", "potion", "tonic", "guard", "ration", "recall", "key", "relic", "quest", "elixir", "shrine", "fountain", "merchant", "machine", "waygate", "altar", "toll", "console", "strongbox", "corpse"]
const FONT_CELL := Vector2i(8, 10)
const FONT_CHARS := [" ", "!", "\"", "#", "$", "%", "&", "'", "(", ")", "*", "+", ",", "-", ".", "/", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", ":", ";", "<", "=", ">", "?", "@", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "[", "\\", "]", "^", "_", "`", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "{", "|", "}", "~", "▶", "♥", "✦", "▼", "▲"]
const FONT_WIDTHS := [3, 1, 3, 5, 5, 5, 5, 1, 2, 2, 5, 5, 2, 4, 1, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 1, 2, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 2, 5, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 1, 3, 4, 2, 5, 4, 4, 4, 4, 3, 4, 4, 4, 5, 5, 4, 4, 4, 3, 1, 3, 5, 4, 5, 5, 5, 5]
