# GENERATED by tools/gen_data.py from ../src/monsters.c -- do not edit by hand.
# Re-run the generator after changing the C tables.
class_name MonstersData

## The hand-authored roster per depth tier:
## [name, glyph, family, hp, atk, def, xp, gold]
const CURATED := [
	[
		["Vine Rat", "r", 0, 11, 4, 0, 4, 2],
		["Bog Leech", "l", 0, 10, 5, 0, 4, 2],
		["Quill-Back Boar", "b", 0, 20, 7, 2, 7, 5],
		["Canopy Adder", "s", 0, 11, 8, 1, 6, 3],
		["Tribal Skirmisher", "a", 0, 17, 9, 2, 7, 6],
		["Tribal Shaman", "m", 0, 14, 10, 1, 8, 6],
		["River Pirate", "i", 0, 16, 8, 2, 7, 8],
		["Canopy Stalking Cat", "f", 0, 15, 9, 1, 7, 4],
	],
	[
		["Rusted Automaton", "A", 1, 30, 7, 4, 12, 10],
		["Steam Hound", "h", 1, 22, 9, 2, 10, 8],
		["Company Enforcer", "E", 1, 26, 8, 5, 13, 14],
		["Pressure Wraith", "w", 1, 18, 11, 1, 11, 9],
		["Company Deserter", "d", 1, 28, 9, 4, 13, 16],
		["Scrap Clan Raider", "C", 1, 24, 10, 3, 12, 12],
		["Steam Pirate Boarder", "B", 1, 26, 9, 3, 13, 20],
		["Boiler Wisp", "e", 1, 16, 11, 1, 11, 9],
	],
	[
		["Crystal Wraith", "W", 2, 45, 14, 6, 22, 20],
		["Star-iron Golem", "G", 2, 70, 12, 12, 28, 26],
		["Vent Wisp", "w", 2, 30, 16, 3, 20, 16],
		["Buried King's Echo", "k", 2, 50, 15, 8, 25, 22],
		["Ruin Cultist", "C", 2, 38, 15, 5, 23, 18],
		["Crystal-Touched Zealot", "z", 2, 42, 16, 6, 24, 20],
		["Relic Hunter", "u", 2, 36, 14, 7, 22, 30],
		["Deep Ruin Stalker", "D", 2, 40, 17, 4, 23, 16],
		["Star-iron Sentinel", "I", 2, 75, 18, 14, 30, 28],
		["The Ward Unclaimed", "P", 2, 55, 20, 9, 32, 35],
		["Builder's Remnant", "B", 2, 90, 16, 16, 33, 30],
		["Sealed-Door Wraith", "V", 2, 48, 22, 7, 28, 24],
		["Record-Hall Keeper", "K", 2, 65, 19, 11, 31, 32],
	],
	[
		["Hollow Shade", "S", 3, 60, 20, 8, 38, 34],
		["Cold Patch", "c", 3, 40, 24, 4, 34, 28],
		["Silent Stalker", "t", 3, 75, 22, 10, 42, 38],
		["Salt-Broken Warden", "x", 3, 90, 18, 14, 44, 40],
		["Salt Nomad", "n", 3, 55, 21, 7, 36, 30],
		["Outrider Cultist", "u", 3, 50, 23, 6, 37, 28],
		["Wasteland Raider", "B", 3, 58, 22, 8, 38, 34],
		["Ash-Choked Horror", "F", 3, 80, 19, 11, 40, 30],
		["Salt-Iron Revenant", "I", 3, 95, 25, 12, 45, 36],
		["The Unspoken Name", "T", 3, 70, 27, 8, 46, 34],
		["Djinn-Touched Miner", "M", 3, 85, 23, 10, 42, 38],
		["Ash-Wrapped Prospector", "P", 3, 78, 24, 9, 41, 40],
		["Salt-Ring Breaker", "K", 3, 100, 26, 13, 48, 42],
	],
	[
		["Root Horror", "R", 4, 110, 28, 14, 60, 55],
		["Ember Revenant", "v", 4, 90, 34, 10, 58, 52],
		["Chained Warden", "&", 4, 150, 26, 20, 70, 65],
		["Abyss Cult Zealot", "z", 4, 100, 30, 12, 62, 50],
		["Drowned Pirate Captain", "C", 4, 130, 32, 16, 75, 90],
		["Wellspring Wraith", "W", 4, 95, 33, 10, 60, 48],
		["Cinder Wretch", "g", 4, 85, 29, 9, 58, 45],
		["Star-Forge Guardian", "I", 4, 160, 35, 22, 80, 70],
		["The Herald's Shadow", "J", 4, 140, 38, 18, 85, 75],
		["Nine-Hearth Wraith", "N", 4, 130, 36, 16, 78, 68],
		["Outrider-Touched Colossus", "O", 4, 180, 33, 24, 82, 72],
		["The Well's Last Custodian", "U", 4, 155, 37, 20, 88, 80],
	],
]

const PREFIXES := [
	["Vine", "Bog", "Moss", "Root", "Thorn", "Fang", "Claw", "River", "Canopy", "Swamp", "Feral", "Wild", "Mud", "Reed", "Leech", "Howling", "Prowling", "Sunken"],
	["Rusted", "Steam", "Company", "Scrap", "Boiler", "Piston", "Riveted", "Pressure", "Coal", "Clockwork", "Soot", "Iron", "Brass", "Corroded", "Sparking", "Leaking", "Grinding", "Discarded"],
	["Crystal", "Star-iron", "Buried", "Ruin", "Deep", "Hollow", "Ancient", "Sunken", "Cracked", "Silent", "Glass", "Echoing", "Forgotten", "Ashen", "Drowned", "Pale", "Ghostly", "Shattered"],
	["Salt", "Hollow", "Cold", "Silent", "Ash", "Outrider", "Wasteland", "Bone", "Dust", "Sand", "Grey", "Nomad", "Broken", "Withered", "Cracked", "Bleached", "Whispering", "Forsaken"],
	["Root", "Ember", "Chained", "Abyss", "Drowned", "Wellspring", "Cinder", "Void", "Black", "Molten", "Weeping", "Screaming", "Ashen", "Ancient", "Deep", "Hungering", "Burning", "Sunken"],
]

const NOUNS := [
	["Rat", "Adder", "Boar", "Stalker", "Skirmisher", "Shaman", "Pirate", "Cat", "Lurker", "Raider", "Wretch", "Howler", "Warband", "Prowler", "Biter"],
	["Automaton", "Hound", "Enforcer", "Wraith", "Deserter", "Raider", "Boarder", "Wisp", "Sentry", "Golem", "Drone", "Trooper", "Guard", "Hulk", "Servitor"],
	["Wraith", "Golem", "Wisp", "Echo", "Cultist", "Zealot", "Hunter", "Stalker", "Guardian", "Warden", "Sentinel", "Watcher", "Remnant", "Husk", "Shade"],
	["Shade", "Patch", "Stalker", "Warden", "Nomad", "Cultist", "Raider", "Horror", "Wanderer", "Reaver", "Drifter", "Husk", "Watcher", "Fiend", "Marauder"],
	["Horror", "Revenant", "Warden", "Zealot", "Captain", "Wraith", "Wretch", "Behemoth", "Terror", "Devourer", "Specter", "Colossus", "Fiend", "Herald", "Abomination"],
]

## Average baseline per tier for the generated variants: hp, atk, def, xp, gold
const TIER_BASE := [
	[14.0, 7.0, 1.0, 6.0, 4.0],
	[24.0, 9.0, 3.0, 12.0, 12.0],
	[44.0, 15.0, 6.0, 23.0, 21.0],
	[64.0, 21.0, 9.0, 39.0, 33.0],
	[109.0, 30.0, 13.0, 63.0, 58.0],
]

## Variant archetypes (Grunt, Brute, Skirmisher, Ambusher, Tank, Glass Cannon,
## Veteran, Swarmling): multipliers on hp, atk, def, xp, gold
const ARCHETYPES := [
	[1.00, 1.00, 1.00, 1.00, 1.00],
	[1.30, 1.15, 1.10, 1.15, 1.10],
	[0.85, 1.20, 0.80, 1.05, 1.00],
	[0.80, 1.30, 0.70, 1.10, 1.05],
	[1.40, 0.85, 1.40, 1.10, 1.00],
	[0.70, 1.40, 0.60, 1.15, 1.10],
	[1.15, 1.10, 1.15, 1.20, 1.20],
	[0.60, 0.80, 0.60, 0.70, 0.60],
]
