#include "talisman.h"

const char *ending_name[END_COUNT] = {
    "the Crown of Command", "the Demon Lord", "Pandora's Box",
    "the Belt of Hercules", "a Horrible Black Void", "the Dragon King"
};

const char *set_name[SET_COUNT] = {
    "Base Game", "The Reaper", "The Frostmarch", "The Sacred Pool",
    "The Blood Moon", "The Firelands", "The Cataclysm", "The Dungeon",
    "The Highland", "The Woodland", "The Harbinger",
    "City deck", "Timescape deck"
};



/* ---- Outer Region: 24 spaces, clockwise from the top-left corner ---- */
const Space outer_ring[OUTER_N] = {
    {"Village",    SP_VILLAGE,  0},
    {"Fields",     SP_ADV,      1},
    {"Woods",      SP_ADV,      1},
    {"SENTINEL",   SP_SENTINEL, 0},   /* idx 3  - crossing inward */
    {"Ruins",      SP_ADV,      2},
    {"Tavern",     SP_TAVERN,   0},
    {"Crags",      SP_ADV,      1},
    {"Chapel",     SP_CHAPEL,   0},
    {"Graveyard",  SP_GRAVE,    0},
    {"Hills",      SP_ADV,      2},
    {"Forest",     SP_ADV,      1},
    {"Cave",       SP_ADV,      2},
    {"City",       SP_CITY,     0},
    {"Plains",     SP_ADV,      1},
    {"Fields",     SP_ADV,      1},
    {"Woods",      SP_ADV,      1},
    {"Ruins",      SP_ADV,      2},
    {"Marsh",      SP_ADV,      2},
    {"Barrow",     SP_CRYPT,    0},
    {"Watchtower", SP_ADV,      1},
    {"Menhir",     SP_ADV,      1},
    {"Thicket",    SP_ADV,      1},
    {"Old Bridge", SP_ADV,      1},
    {"Shrine",     SP_TEMPLE,   0},
};

/* ---- Middle Region: 16 spaces ---- */
const Space middle_ring[MIDDLE_N] = {
    {"HiddenVale",  SP_ADV,    1},
    {"CursedGlade", SP_ADV,    2},
    {"Crossing",    SP_ADV,    1},   /* idx 2  - arrival from Sentinel */
    {"Dungeon",     SP_ADV,    2},
    {"VampireTwr",  SP_CRYPT,  0},
    {"WerewolfDen", SP_ADV,    2},
    {"Temple",      SP_TEMPLE, 0},   /* idx 6  - chance of a Talisman  */
    {"Pits",        SP_PIT,    0},
    {"Mines",       SP_MINE,   0},
    {"Desert",      SP_DESERT, 0},
    {"PORTAL",      SP_PORTAL, 0},   /* idx 10 - crossing inward       */
    {"Oasis",       SP_CHAPEL, 0},
    {"Chasm",       SP_PIT,    0},
    {"BlackKnight", SP_ADV,    2},
    {"Runes",       SP_ADV,    1},
    {"Crypt",       SP_CRYPT,  0},
};

/* ---- Inner Region: 8 spaces, one step per turn ---- */
const Space inner_ring[INNER_N] = {
    {"PlainPeril", SP_DESERT, 0},
    {"DREAD GATE", SP_GATE,   0},   /* idx 1 - step into the Crown */
    {"Werewolf",   SP_WEREDEN,   0},
    {"ValleyFire", SP_FIRE,   0},
    {"Pit Fiend",  SP_PITFIENDS, 0},
    {"Threshold",  SP_PLAIN,  0},   /* idx 5 - arrival from Portal */
    {"ValleyFire", SP_FIRE,   0},
    {"PlainPeril", SP_DESERT, 0},
};

const Space crown_space = {"CROWN", SP_CROWN_SP, 0};

/* The City, transcribed from the board in 2e-Tal-Is-Poor.zip.  The rules
 * say it "remains part of the Outer Region" and moves the same way -- roll
 * a die and go that many spaces -- so it is a plain ring.  Streets and
 * Locations alternate, which is how the board keeps rule (b): "it is
 * impossible to get from one Location to another without first going"
 * through the street between them.
 *
 * The board carries one Location this does not: the Anarchists' Guild,
 * whose whole effect is changing Alignment, and Alignment has no mechanics
 * here yet.  The Donjon is not on the ring at all -- you only reach it by
 * being arrested -- so it is a Region of its own at the middle of the board. */
const Space city_ring[CITY_N] = {
    {"CITY GATE",  SP_C_GATE,        0},
    {"High Temple",SP_C_TEMPLE,      0},
    {"FlaskStreet",SP_ADV,           1},
    {"Apothecary", SP_C_APOTHECARY,  0},
    {"Gold Lane",  SP_ADV,           1},
    {"The Bank",   SP_C_BANK,        0},
    {"ImperialAve",SP_ADV,           1},
    {"The Wharf",  SP_C_WHARF,       0},
    {"NorthAlley", SP_ADV,           2},
    {"6 Fates Inn",SP_C_INN,         0},
    {"GuildsStrt", SP_ADV,           1},
    {"Armoury",    SP_C_ARMOURY,     0},
    {"DroppingsLn",SP_ADV,           1},
    {"Stables",    SP_C_STABLES,     0},
    {"TempleStrt", SP_ADV,           1},
    {"Surgery",    SP_C_SURGERY,     0},
    {"SpeakersCnr",SP_ADV,           1},
    {"Town Square",SP_C_SQUARE,      0},
    {"Pentagram",  SP_ADV,           1},
    {"Enchantress",SP_C_ENCHANTRESS, 0},
    {"TempleSqre", SP_ADV,           1},
    {"MagicEmprm", SP_C_EMPORIUM,    0},
    {"Castle Way", SP_ADV,           1},
    {"RoyalCastle",SP_C_CASTLE,      0},
};

const Space donjon_space = {"DONJON", SP_C_DONJON, 0};

/* The Timescape.  The space names and every effect below are real -- they
 * come off the board and from the Talisman Timescape Data Sheet, which the
 * rulebook reproduces in full.  Movement is real too: the board's own
 * legend reads "Follow the coloured warp line corresponding with the dice
 * roll shown below: 1,2 -- 3,4 -- 5,6.  Movement is One Way Only (except
 * from the Time Loop)."  So every reality has three exits and you have no
 * say in which you take. */
const Space time_scape[TIME_N] = {
    {"WARP GATE",  SP_T_WARPGATE,   0},   /*  0  "Your Turn ends here."     */
    {"4thDimensn", SP_T_DRAW,       0},   /*  1                             */
    {"Warp Demon", SP_T_DEMON,      0},   /*  2                             */
    {"Limbo",      SP_T_DRAW,       0},   /*  3                             */
    {"Time Loop",  SP_T_TIMELOOP,   0},   /*  4                             */
    {"NegativeZne",SP_T_DRAW,       0},   /*  5                             */
    {"AstralPlane",SP_T_DRAW,       0},   /*  6                             */
    {"Nexus",      SP_T_NEXUS,      0},   /*  7                             */
    {"VORTEX",     SP_T_VORTEX,     0},   /*  8  the way home               */
    {"Rad Zone",   SP_T_RADZONE,    0},   /*  9                             */
    {"Planetfall", SP_T_DRAW,       0},   /* 10  draws two                  */
    {"RealmChaos", SP_T_DRAW,       0},   /* 11                             */
    {"Death World",SP_T_DEATHWORLD, 0},   /* 12                             */
    {"The Void",   SP_T_DRAW,       0},   /* 13                             */
    {"SpaceFortrs",SP_T_FORTRESS,   0},   /* 14                             */
    {"SentinelOut",SP_T_SENTINEL,   0},   /* 15                             */
};

/* The one part of this board that is ours rather than theirs.  The warp
 * lines on the scan cross and overlap so heavily that tracing 48 directed
 * edges off it reliably is not possible, and a half-traced graph presented
 * as the real one would be worse than an honest substitute.  So the lines
 * are generated: from each reality the 1-2 line steps 1 on, the 3-4 line 5
 * on and the 5-6 line 11 on.  All three are coprime with 16, which makes
 * the board strongly connected -- every reality can reach the Vortex, and
 * so nobody is ever stranded. */
const int warp_line[TIME_N][3] = {
    { 1, 5, 11}, { 2, 6, 12}, { 3, 7, 13}, { 4, 8, 14},
    { 5, 9, 15}, { 6,10,  0}, { 7,11,  1}, { 8,12,  2},
    { 9,13,  3}, {10,14,  4}, {11,15,  5}, {12, 0,  6},
    {13, 1,  7}, {14, 2,  8}, {15, 3,  9}, { 0, 4, 10},
};

/* The Dungeon, transcribed from the board in 2e-Tal-Is-Poor.zip.  It is a
 * spiral: "the Entrance at the outside of the board and the end of the
 * dungeon, the Treasure Chamber, at the center", walked as one path.  The
 * laps are 16 then 8, which is the perimeter of a 5x5 then a 3x3 -- so the
 * same nested-square geometry as the main board draws it. */
const Space dungeon_path[DUNGEON_N] = {
    /* --- the outer lap, anticlockwise from the door --- */
    {"ENTRANCE",   SP_D_ENTRANCE, 0},
    {"Corridor",   SP_ADV,        1},
    {"Cavern",     SP_ADV,        1},
    {"Corridor",   SP_ADV,        1},
    {"Guard Room", SP_D_GUARD,    0},
    {"Corridor",   SP_ADV,        1},
    {"Corridor",   SP_ADV,        1},
    {"Library",    SP_D_LIBRARY,  0},
    {"Tunnel",     SP_ADV,        1},
    {"Tunnel",     SP_ADV,        1},
    {"Vault",      SP_ADV,        2},
    {"Corridor",   SP_ADV,        1},
    {"Cell",       SP_D_CELL,     0},
    {"Tunnel",     SP_ADV,        1},
    {"Cavern",     SP_ADV,        1},
    {"Torture Rm", SP_D_TORTURE,  0},
    /* --- the inner lap --- */
    {"Corridor",   SP_ADV,        1},
    {"Cavern",     SP_ADV,        1},
    {"Dark Room",  SP_D_DARK,     0},
    {"Corridor",   SP_ADV,        1},
    {"Corridor",   SP_ADV,        1},
    {"Kitchen",    SP_D_KITCHEN,  0},
    {"Corridor",   SP_ADV,        1},
    {"Cavern",     SP_ADV,        1},
    /* --- the end of it --- */
    {"TREASURE",   SP_D_TREASURE, 0},
};

/* The main board's four Regions.  `base` is each Region's first space_id,
 * and the values below are exactly what the old hand-written space_id()
 * switch produced -- 0, 24, 40, 48 -- so no resident card, gold pile or
 * dropped Talisman moves as a result of this table existing. */
const RegionDef region_tbl[] = {
    {"Outer",  outer_ring,   OUTER_N,  TOPO_RING,  0,                        0},
    {"Middle", middle_ring,  MIDDLE_N, TOPO_RING,  OUTER_N,                  0},
    {"Inner",  inner_ring,   INNER_N,  TOPO_RING,  OUTER_N + MIDDLE_N,       0},
    {"Crown",  &crown_space, 1,        TOPO_RING,  OUTER_N + MIDDLE_N + INNER_N, 0},
    /* The rulebook's own framing: the Dungeon "counts as a Region".  It is
     * a PATH -- "you may only move towards the center". */
    {"Dungeon", dungeon_path, DUNGEON_N, TOPO_PATH, MAINBOARD_N,             1},
    {"City",    city_ring,    CITY_N,    TOPO_RING, MAINBOARD_N + DUNGEON_N, 2},
    {"Donjon",  &donjon_space, 1,        TOPO_RING, MAINBOARD_N + DUNGEON_N + CITY_N, 2},
    {"Timescape", time_scape, TIME_N, TOPO_WARP, MAINBOARD_N + DUNGEON_N + CITY_N + 1, 3},
};
const int region_count = (int)(sizeof region_tbl / sizeof region_tbl[0]);

/* One board so far.  The four Regions above share its 7x7 grid, which is
 * why a board owns a run of Regions rather than being one. */
const BoardDef board_tbl[] = {
    {"The Kingdom", REG_OUTER,   4, GRID, GRID},
    {"The Dungeon", REG_DUNGEON, 1, GRID, GRID},
    {"The City",    REG_CITY,    2, GRID, GRID},
    {"The Timescape", REG_TIME,  1, GRID, GRID},
};
const int board_count = (int)(sizeof board_tbl / sizeof board_tbl[0]);

/* ---- Characters ---- */
/* The fourteen characters of the official 2nd Edition box.  Strength,
 * Craft, Lives and Gold come from CHARACTERS.tsv (talisman.edwebb.net);
 * alignment, starting space and the abilities come from the printed cards
 * themselves, OCR'd out of the print-and-play sheets -- see
 * CHARACTERS-2e.tsv and extract-2e-characters.py.
 *
 * Fate is the one number no source gave: the 2e cards do not print it and
 * the database column is empty for every 2e row, so these are this game's
 * own, set from how much luck each character looks like it should carry. */
const CharTemplate char_tbl[] = {
    {"Warrior",    4, 3, 4, 3, 1, AB_TWO_WEAPONS | AB_COMBAT_2DICE,
     AL_NEUTRAL, "Tavern",    NULL,     0, SET_BASE,
     "rolls two combat dice and keeps the higher; wields two Weapons",
     "Strong arm, slow wits."},
    {"Wizard",     2, 5, 4, 3, 1, AB_ALWAYS_SPELL | AB_PSYCHIC_ATTACK,
     AL_EVIL,    "Graveyard", NULL,     2, SET_BASE,
     "begins with two Spells and is never without one",
     "Feeble, but the spirits fear him."},
    {"Elf",        3, 4, 4, 4, 1, 0u,
     AL_GOOD,    "Forest",    "Forest", 0, SET_BASE,
     "the Forest never troubles him",
     "Lucky, balanced, quick."},
    {"Dwarf",      3, 3, 4, 3, 1, AB_MINER,
     AL_NEUTRAL, "Crags",     "Crags",  0, SET_BASE,
     "safe in the Crags, and rolls only two dice in the Mines",
     "Tough and rich, unlucky."},
    {"Priest",     2, 4, 4, 4, 1, AB_DESTROY_SPIRIT | AB_NO_SWORD,
     AL_GOOD,    "Chapel",    NULL,     1, SET_BASE,
     "destroys any Spirit outright, but bears no Sword",
     "Turns away the restless dead."},
    {"Thief",      3, 3, 4, 4, 1, AB_STEAL,
     AL_EVIL,    "City",      NULL,     0, SET_BASE,
     "steals an Object or Gold from anyone he lands on",
     "Light fingers, lighter conscience."},
    {"Troll",      6, 1, 4, 2, 1, 0u,
     AL_NEUTRAL, "Crags",     "Crags",  0, SET_BASE,
     "the Crags never trouble him",
     "Enormous, and slow about it."},
    {"Monk",       2, 3, 4, 4, 1, AB_CRAFT_TO_STR | AB_NO_SWORD,
     AL_GOOD,    "Village",   NULL,     0, SET_BASE,
     "adds his Craft to his Strength in combat, but bears no Sword",
     "His hands are the weapon."},
    {"Sorceress",  2, 4, 4, 4, 1, AB_ENCHANT | AB_PSYCHIC_ATTACK | AB_EVADE_SPIRIT,
     AL_EVIL,    "Graveyard", NULL,     1, SET_BASE,
     "Enchants instead of attacking: her victim loses a turn",
     "She would rather you simply stopped."},
    {"Prophetess", 2, 4, 4, 5, 1, AB_ALWAYS_SPELL | AB_DRAW_EXTRA,
     AL_GOOD,    "Chapel",    NULL,     1, SET_BASE,
     "draws one Adventure card more than she needs, and discards one",
     "She has read the ending already."},
    {"Ghoul",      2, 4, 4, 3, 1, AB_PSYCHIC_ATTACK | AB_LIFE_STEAL,
     AL_EVIL,    "Graveyard", NULL,     0, SET_BASE,
     "a Life taken in Psychic Combat becomes her own",
     "It feeds, and it remembers."},
    {"Druid",      2, 4, 4, 4, 1, AB_ANY_ALIGN,
     AL_NEUTRAL, "Forest",    "Forest", 1, SET_BASE,
     "the Forest never troubles him",
     "He keeps older company than kings."},
    {"Minstrel",   2, 4, 4, 4, 1, AB_CHARM_ANIMAL,
     AL_GOOD,    "Tavern",    NULL,     0, SET_BASE,
     "Animals will not attack him",
     "A song for a supper, and safe passage."},
    {"Assassin",   3, 3, 4, 4, 1, AB_ASSASSINATE,
     AL_EVIL,    "City",      NULL,     0, SET_BASE,
     "when he attacks, his victim adds no die to their score",
     "The knife arrives before the man."},

    /* Eight more 2e Characters whose cards are in CHARACTERS-2e.tsv and were
     * never entered.  Two of them are the missing subjects of rules I had
     * written off as unimplementable: the Witch Doctor's Evil Eye is what
     * causes a Curse, and the Samurai is the one who carries a Bow. */
    {"Witch Doctor", 2, 4, 4, 3, 1, AB_EVIL_EYE,
     AL_EVIL,    "Graveyard", NULL,     1, SET_BASE,
     "may Curse a Character instead of fighting them",
     "The eye that sees you does not blink."},
    {"Samurai",     4, 2, 4, 3, 1, AB_BOW,
     AL_NEUTRAL, "Village",   NULL,     0, SET_BASE,
     "may fire his Bow at range instead of moving",
     "One arrow, one breath."},
    {"Questing Kn", 4, 3, 4, 3, 1, 0u,
     AL_GOOD,    "Chapel",    NULL,     0, SET_BASE,
     "starts with Sword, Shield, Helmet and Armour; will not stoop to easy prey",
     "The vow was made before the sword."},
    {"Soldier",     4, 3, 4, 3, 1, 0u,
     AL_GOOD,    "City",      NULL,     0, SET_BASE,
     "starts with a Helmet and Sword; unmoved by the Patrol and the Raiders",
     "Paid, fed, and pointed at the horizon."},
    {"Vampire",     3, 3, 4, 3, 1, AB_PSYCHIC_ATTACK,
     AL_EVIL,    "Graveyard", NULL,     0, SET_BASE,
     "safe in the Forest; may Rout a Character he defeats in Combat",
     "He keeps no mirror."},
    {"Orc",         2, 2, 4, 3, 1, 0u,
     AL_EVIL,    "Crags",     NULL,     0, SET_BASE,
     "safe in the Crags; may take Goblins, Hobgoblins and Wolves as Followers",
     "It counts in kills, not coins."},
    {"Dragon Prst", 2, 4, 4, 3, 1, 0u,
     AL_EVIL,    "Graveyard", NULL,     1, SET_BASE,
     "may take a Spell instead of a Strength point when trading Enemies in",
     "He reads the smoke."},
    {"Dragon Rider",3, 3, 4, 3, 1, 0u,
     AL_NEUTRAL, "Forest",    NULL,     0, SET_BASE,
     "safe in the Forest if she wishes; fights Dragons the better for knowing them",
     "She learned the wingbeat before the word."},    /* --- the expansions add playable characters too, not just cards;
     *     each appears only when its set is shuffled in --- */
    {"Amazon", 4, 2, 4, 3, 1, 0u,
     AL_NEUTRAL, "Village", NULL, 0, SET_BASE,
     "may roll two movement dice; may ignore a lost Combat and flee", "From the Expansion set."},
    {"Archaeologis", 2, 4, 4, 3, 1, 0u,
     AL_GOOD, "VORTEX", NULL, 0, SET_TIMED,
     "Timescape set; her card text is not transcribed yet", "From the Timescape set."},
    {"Astronaut", 3, 3, 4, 3, 1, 0u,
     AL_NEUTRAL, "SpaceFortrs", NULL, 0, SET_TIMED,
     "Timescape set; her card text is not transcribed yet", "From the Timescape set."},
    {"Astropath", 2, 4, 4, 3, 1, 0u,
     AL_NEUTRAL, "WARP GATE", NULL, 0, SET_TIMED,
     "starts with a Spell and 3 Gold; chooses her Warp Line, and may attack psychically", "From the Timescape set."},
    {"Barbarian", 5, 1, 4, 3, 1, 0u,
     AL_NEUTRAL, "Forest", NULL, 0, SET_BASE,
     "safe in the Forest, Crags and Chasm; wins more than a Life when he attacks", "From the Expansion set."},
    {"Chainsaw War", 4, 2, 4, 3, 1, 0u,
     AL_NEUTRAL, "VORTEX", NULL, 0, SET_TIMED,
     "starts with the Chainsword and Medi-Kit; rolls two Combat dice; never Panicked", "From the Timescape set."},
    {"Conjurer", 2, 4, 4, 3, 1, 0u,
     AL_GOOD, "Chapel", NULL, 0, SET_DUNGEON,
     "starts with a Spell and is never without one; may hold more than one", "From the Dungeon set."},
    {"Cyborg", 5, 1, 4, 3, 1, 0u,
     AL_EVIL, "VORTEX", NULL, 0, SET_TIMED,
     "may add 1 to his movement roll; his armoured body deflects some blows", "From the Timescape set."},
    {"Dark Elf", 3, 4, 4, 3, 1, 0u,
     AL_EVIL, "Graveyard", NULL, 0, SET_DUNGEON,
     "may drain a Follower's life-force into her own Lives", "From the Dungeon set."},
    {"Gipsy", 2, 4, 4, 3, 1, 0u,
     AL_GOOD, "Forest", NULL, 0, SET_DUNGEON,
     "foretelling: may refuse any Event she draws; starts with a Spell", "From the Dungeon set."},
    {"Gladiator", 4, 2, 4, 3, 1, 0u,
     AL_EVIL, "Tavern", NULL, 0, SET_BASE,
     "Expansion set; her card text is not transcribed yet", "From the Expansion set."},
    {"Halfling", 2, 3, 4, 3, 1, 0u,
     AL_NEUTRAL, "Village", NULL, 0, SET_BASE,
     "Expansion set; her card text is not transcribed yet", "From the Expansion set."},
    {"Highlander", 3, 3, 4, 3, 1, 0u,
     AL_NEUTRAL, "Crags", NULL, 0, SET_DUNGEON,
     "may Charge for +2 in Combat, then misses his next Turn recovering", "From the Dungeon set."},
    {"Hobgoblin", 3, 3, 4, 3, 1, 0u,
     AL_EVIL, "Crags", NULL, 0, SET_BASE,
     "safe in the Crags; takes Goblins as Followers, who add their Strength", "From the Expansion set."},
    {"Inquisitor", 2, 4, 4, 3, 1, 0u,
     AL_NEUTRAL, "City", NULL, 0, SET_DUNGEON,
     "picks his Alignment after everyone else, and converts those who differ", "From the Dungeon set."},
    {"Knight", 3, 3, 4, 3, 1, 0u,
     AL_GOOD, "Chapel", NULL, 0, SET_BASE,
     "in Combat with another player, his Strength rises to match theirs", "From the Expansion set."},
    {"Leprechaun", 2, 4, 4, 3, 1, 0u,
     AL_GOOD, "Forest", NULL, 0, SET_BASE,
     "starts with two Spells; safe in the Forest; a 6 teleports him anywhere near", "From the Expansion set."},
    {"Martial Arti", 3, 3, 4, 3, 1, 0u,
     AL_NEUTRAL, "Village", NULL, 0, SET_DUNGEON,
     "may attempt a Killer Blow: one die, 5 or 6 wins the Combat outright", "From the Dungeon set."},
    {"Merchant", 2, 3, 4, 3, 3, 0u,
     AL_NEUTRAL, "City", NULL, 0, SET_BASE,
     "starts with extra Gold; buys off Goblins and Ogres, and trades instead of fighting", "From the Expansion set."},
    {"Minotaur", 5, 2, 4, 3, 1, 0u,
     AL_EVIL, "Crags", NULL, 0, SET_CITYD,
     "safe in the Crags; untouched by the Maze and the Siren; wears no Helmet", "From the City set."},
    {"Necromancer", 3, 3, 4, 3, 1, 0u,
     AL_EVIL, "Graveyard", NULL, 0, SET_BASE,
     "Expansion set; her card text is not transcribed yet", "From the Expansion set."},
    {"Philosopher", 2, 4, 4, 3, 1, 0u,
     AL_NEUTRAL, "City", NULL, 0, SET_BASE,
     "starts with a Spell; always knows the top Adventure card, and may reroll moves", "From the Expansion set."},
    {"Pilgrim", 2, 4, 4, 3, 1, 0u,
     AL_GOOD, "Chapel", NULL, 0, SET_BASE,
     "Expansion set; her card text is not transcribed yet", "From the Expansion set."},
    {"Pirate", 4, 2, 4, 3, 1, 0u,
     AL_EVIL, "Tavern", NULL, 0, SET_DUNGEON,
     "Dungeon set; her card text is not transcribed yet", "From the Dungeon set."},
    {"Ranger", 3, 3, 4, 3, 1, 0u,
     AL_GOOD, "Village", NULL, 0, SET_BASE,
     "safe in Crags, Forest and Chasm; ignores Storm, Blizzard and the Desert", "From the Expansion set."},
    {"Rogue", 3, 3, 4, 3, 1, 0u,
     AL_EVIL, "Tavern", NULL, 0, SET_BASE,
     "starts with a Spell; takes a Spell from anyone she lands on, sight unseen", "From the Expansion set."},
    {"Saracen", 3, 3, 4, 3, 1, 0u,
     AL_EVIL, "Crags", NULL, 0, SET_DUNGEON,
     "Dungeon set; her card text is not transcribed yet", "From the Dungeon set."},
    {"Satyr", 2, 4, 4, 3, 1, 0u,
     AL_EVIL, "Crags", NULL, 0, SET_BASE,
     "Expansion set; her card text is not transcribed yet", "From the Expansion set."},
    {"Scientist", 2, 5, 4, 3, 1, 0u,
     AL_NEUTRAL, "VORTEX", NULL, 0, SET_TIMED,
     "never without a Spell once she has one; may repair the Ancient Artifact", "From the Timescape set."},
    {"Scout", 3, 3, 4, 3, 1, 0u,
     AL_NEUTRAL, "Crags", NULL, 0, SET_DUNGEON,
     "safe in Forest and Crags; fights better in Woods and Hills; reads Places early", "From the Dungeon set."},
    {"Space Marine", 3, 2, 4, 3, 1, 0u,
     AL_NEUTRAL, "WARP GATE", NULL, 0, SET_TIMED,
     "Timescape set; her card text is not transcribed yet", "From the Timescape set."},
    {"Space Pirate", 4, 3, 4, 3, 1, 0u,
     AL_EVIL, "WARP GATE", NULL, 0, SET_TIMED,
     "Timescape set; her card text is not transcribed yet", "From the Timescape set."},
    {"Sprite", 1, 5, 4, 3, 1, 0u,
     AL_GOOD, "Forest", NULL, 0, SET_DUNGEON,
     "safe in the Forest; starts with two Spells and always holds at least two", "From the Dungeon set."},
    {"Spy", 3, 3, 4, 3, 1, 0u,
     AL_EVIL, "City", NULL, 0, SET_DUNGEON,
     "turns a Stranger into her own agent, whom only she may visit", "From the Dungeon set."},
    {"Swashbuckler", 3, 3, 4, 3, 1, 0u,
     AL_GOOD, "Tavern", NULL, 0, SET_DUNGEON,
     "an extra Turn when he wins a Combat on his own, once a round", "From the Dungeon set."},
    {"Swordsman", 3, 3, 4, 3, 1, 0u,
     AL_NEUTRAL, "Village", NULL, 0, SET_DUNGEON,
     "Dungeon set; her card text is not transcribed yet", "From the Dungeon set."},
    {"Valkyrie", 3, 4, 4, 3, 1, 0u,
     AL_GOOD, "Graveyard", NULL, 0, SET_CITYD,
     "City set; her card text is not transcribed yet", "From the City set."},
    {"Zulu", 5, 2, 4, 3, 1, 0u,
     AL_NEUTRAL, "Forest", NULL, 0, SET_DUNGEON,
     "a fan-made character (Earl Wynn, New Timescape)", "From the Dungeon set."},
    { .cls = NULL }
};

/* the table is NULL-terminated, so the sentinel is not a character */
const int char_count = (int)(sizeof char_tbl / sizeof char_tbl[0]) - 1;

/* ---- Adventure deck ---- */
/* The Adventure deck, generated from the published base-game card list:
 * 80 distinct cards, 104 in total.  The list supplies names, types and
 * copy counts; the Strength/Craft numbers are ours. */
/* Adventure decks, generated from the published card lists.  Names, types
 * and copy counts are the real ones; Strength/Craft values and the exact
 * effects are ours -- the lists carry no numbers. */
const Card deck_proto[] = {
    /* ---- SET_BASE ---- */
    {.name="Doorway", .type=C_PLACE, .place=PLACE_DOORWAY, .copies=4, .set=SET_BASE},
    {.name="Ape", .type=C_ENEMY, .animal=1, .power=3, .copies=1, .set=SET_BASE},
    {.name="Bear", .type=C_ENEMY, .animal=1, .power=3, .copies=1, .set=SET_BASE},
    {.name="Lion", .type=C_ENEMY, .animal=1, .power=4, .copies=1, .set=SET_BASE},
    {.name="Serpent", .type=C_ENEMY, .animal=1, .power=2, .copies=1, .set=SET_BASE},
    {.name="Wild Boar", .type=C_ENEMY, .animal=1, .power=3, .copies=2, .set=SET_BASE},
    {.name="Wolf", .type=C_ENEMY, .animal=1, .power=2, .copies=1, .set=SET_BASE},
    {.name="Dragon", .type=C_ENEMY, .power=7, .copies=3, .set=SET_BASE},
    {.name="Bandit", .type=C_ENEMY, .power=4, .copies=2, .set=SET_BASE},
    {.name="Giant", .type=C_ENEMY, .power=6, .copies=1, .set=SET_BASE},
    {.name="Goblin", .type=C_ENEMY, .power=2, .copies=2, .set=SET_BASE},
    {.name="Hobgoblin", .type=C_ENEMY, .power=3, .copies=2, .set=SET_BASE},
    {.name="Ogre", .type=C_ENEMY, .power=5, .copies=2, .set=SET_BASE},
    {.name="Demon", .type=C_SPIRIT, .power=6, .craftfight=1, .copies=1, .set=SET_BASE},
    {.name="Ghost", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=2, .set=SET_BASE},
    {.name="Lemure", .type=C_SPIRIT, .power=2, .craftfight=1, .copies=2, .set=SET_BASE},
    {.name="Shadow", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=2, .set=SET_BASE},
    {.name="Spectre", .type=C_SPIRIT, .power=4, .craftfight=1, .copies=1, .set=SET_BASE},
    {.name="Wraith", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=2, .set=SET_BASE},
    {.name="Angel", .type=C_EVENT, .d_life=1, .copies=1, .set=SET_BASE, .text="a blessing: +1 Life"},
    {.name="Blizzard", .type=C_EVENT, .miss=1, .copies=1, .set=SET_BASE, .text="you shelter from it"},
    {.name="Book of Spells", .type=C_EVENT, .d_craft=1, .copies=1, .set=SET_BASE, .text="+1 Craft"},
    {.name="Devil", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_BASE, .text="he exacts a price"},
    {.name="Evil Darkness", .type=C_EVENT, .d_craft=-1, .copies=1, .set=SET_BASE, .text="-1 Craft"},
    {.name="Imp", .type=C_EVENT, .d_gold=-2, .copies=1, .set=SET_BASE, .text="it makes off with your purse"},
    {.name="Magical Vortex", .type=C_EVENT, .miss=1, .copies=1, .set=SET_BASE, .text="it spins you about"},
    {.name="Market Day", .type=C_EVENT, .d_gold=2, .copies=1, .set=SET_BASE, .text="+2 Gold"},
    {.name="Mephistopheles", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_BASE, .text="a bargain gone wrong"},
    {.name="Pestilence", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_BASE, .text="you sicken"},
    {.name="Raiders", .type=C_EVENT, .d_gold=-3, .copies=1, .set=SET_BASE, .text="they take what you carry"},
    {.name="Siren", .type=C_EVENT, .miss=1, .copies=1, .set=SET_BASE, .text="you listen too long"},
    {.name="Storm", .type=C_EVENT, .miss=1, .copies=1, .set=SET_BASE, .text="you wait it out"},
    {.name="Alchemist", .type=C_FOLLOWER, .d_gold=3, .copies=1, .set=SET_BASE, .text="+3 Gold"},
    {.name="Cursed by a Hag", .type=C_FOLLOWER, .d_craft=-1, .copies=1, .set=SET_BASE, .text="a curse: -1 Craft"},
    {.name="Gnome", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_BASE, .text="+1 Fate"},
    {.name="Guide", .type=C_FOLLOWER, .d_fate=1, .copies=2, .set=SET_BASE, .text="+1 Fate"},
    {.name="Maiden", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_BASE, .text="+1 Craft"},
    {.name="Mercenary", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_BASE, .text="+1 Strength"},
    {.name="Mule", .type=C_FOLLOWER, .carry=2, .copies=1, .set=SET_BASE, .text="carry 2 more Objects"},
    {.name="Pixie", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_BASE, .text="+1 Fate"},
    {.name="Poltergeist", .type=C_FOLLOWER, .d_craft=-1, .copies=1, .set=SET_BASE, .text="it torments you: -1 Craft"},
    {.name="Princess", .type=C_FOLLOWER, .d_craft=1, .copies=2, .set=SET_BASE, .text="+1 Craft"},
    {.name="Unicorn", .type=C_FOLLOWER, .d_craft=1, .d_fate=1, .copies=1, .set=SET_BASE, .text="+1 Craft, +1 Fate"},
    {.name="Amulet", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_BASE, .text="+1 Craft"},
    {.name="Cross", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_BASE, .text="+1 Craft"},
    {.name="Holy Grail", .type=C_OBJECT, .d_craft=1, .d_life=1, .copies=1, .set=SET_BASE, .text="+1 Craft, +1 max Life"},
    {.name="Holy Lance", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_BASE,
     .text="+1 Strength; Good or Neutral only", .kw=KW_WEAPON,
     .needs=NEEDS_GOOD | NEEDS_NEUTRAL},
    {.name="Magic Belt", .type=C_OBJECT, .d_str=2, .copies=1, .set=SET_BASE, .text="+2 Strength"},
    {.name="Orb of Knowledge", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_BASE, .text="+1 Craft"},
    {.name="Potion of Strength", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_BASE, .text="+1 Strength"},
    {.name="Ring", .type=C_OBJECT, .d_fate=1, .copies=1, .set=SET_BASE, .text="+1 Fate"},
    {.name="Runesword", .type=C_OBJECT, .d_str=2, .copies=1, .set=SET_BASE,
     .text="+2 Strength; Evil only", .kw=KW_WEAPON, .needs=NEEDS_EVIL},
    {.name="Solomon's Crown", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_BASE, .text="+1 Craft"},
    {.name="Talisman", .type=C_OBJECT, .talisman=1, .copies=2, .set=SET_BASE, .text="opens the Portal of Power", .util=30},
    {.name="Wand", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_BASE, .text="+1 Craft"},
    {.name="Armour", .type=C_OBJECT, .copies=1, .set=SET_BASE, .text="Armour: it may spare you a Life", .kw=KW_ARMOUR},
    {.name="Axe", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_BASE, .text="+1 Strength", .kw=KW_WEAPON, .util=4},
    {.name="Bag of Gold", .type=C_GOLD, .d_gold=1, .copies=8, .set=SET_BASE, .text="+1 Gold"},
    {.name="Helmet", .type=C_OBJECT, .copies=1, .set=SET_BASE, .text="Armour: it may spare you a Life", .kw=KW_ARMOUR},
    {.name="Raft", .type=C_OBJECT, .copies=1, .set=SET_BASE, .text="cross the river at the start of your next turn", .util=5},
    {.name="Shield", .type=C_OBJECT, .copies=1, .set=SET_BASE, .text="Armour: it may spare you a Life", .kw=KW_ARMOUR},
    {.name="Sword", .type=C_OBJECT, .d_str=1, .copies=2, .set=SET_BASE, .text="+1 Strength", .kw=KW_WEAPON},
    {.name="Two Bags of Gold", .type=C_GOLD, .d_gold=2, .copies=3, .set=SET_BASE, .text="+2 Gold"},
    {.name="Water Bottle", .type=C_OBJECT, .copies=1, .set=SET_BASE, .text="you never thirst in the waste", .util=6},
    {.name="Cave", .type=C_PLACE, .place=PLACE_DEN, .copies=1, .set=SET_BASE, .text="stays here: it breeds"},
    {.name="Fountain of Wisdom", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BASE, .text="stays here: wisdom"},
    {.name="Magic Portal", .type=C_PLACE, .place=PLACE_PORTAL, .copies=1, .set=SET_BASE, .text="stays here: it moves you"},
    {.name="Magic Stream", .type=C_PLACE, .place=PLACE_POOL, .copies=1, .set=SET_BASE, .text="stays here: it heals"},
    {.name="Market", .type=C_PLACE, .place=PLACE_SHOP, .copies=1, .set=SET_BASE, .text="stays here: a market"},
    {.name="Marsh", .type=C_PLACE, .place=PLACE_MARSH, .copies=1, .set=SET_BASE, .text="stays here: it drags you down"},
    {.name="Maze", .type=C_PLACE, .place=PLACE_MAZE, .copies=1, .set=SET_BASE, .text="stays here: you lose the way"},
    {.name="Pool of Life", .type=C_PLACE, .place=PLACE_POOL, .copies=1, .set=SET_BASE, .text="stays here: it heals"},
    {.name="Shrine", .type=C_PLACE, .place=PLACE_SHRINE, .copies=1, .set=SET_BASE, .text="stays here: it heals"},
    {.name="Enchanter", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BASE, .text="stays here: he teaches"},
    {.name="Fairy", .type=C_STRANGER, .place=PLACE_FAIRY, .copies=1, .set=SET_BASE, .text="stays here: she grants Fate"},
    {.name="Healer", .type=C_STRANGER, .place=PLACE_POOL, .copies=1, .set=SET_BASE, .text="stays here: he mends"},
    {.name="Hermit", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BASE, .text="stays here: he teaches"},
    {.name="Mage", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BASE, .text="stays here: he teaches"},
    {.name="Phantom", .type=C_STRANGER, .power=4, .craftfight=1, .place=PLACE_SPIRIT, .copies=1, .set=SET_BASE, .text="stays here: it haunts"},
    {.name="Sorcerer", .type=C_STRANGER, .power=5, .craftfight=1, .place=PLACE_SPIRIT, .copies=1, .set=SET_BASE, .text="stays here: he duels"},
    {.name="Witch", .type=C_STRANGER, .place=PLACE_WITCH, .copies=1, .set=SET_BASE, .text="stays here: her mood decides"},

    /* ---- SET_REAPER ---- */
    {.name="Giant Spider", .type=C_ENEMY, .animal=1, .power=4, .copies=1, .set=SET_REAPER},
    {.name="Mammoth", .type=C_ENEMY, .animal=1, .power=4, .copies=1, .set=SET_REAPER},
    {.name="Pack of Wolves", .type=C_ENEMY, .animal=1, .power=4, .copies=1, .set=SET_REAPER},
    {.name="Raging Bull", .type=C_ENEMY, .animal=1, .power=3, .copies=1, .set=SET_REAPER},
    {.name="Sabertooth Tiger", .type=C_ENEMY, .animal=1, .power=4, .copies=1, .set=SET_REAPER},
    {.name="Wight", .type=C_ENEMY, .power=4, .copies=1, .set=SET_REAPER},
    {.name="Stone Golem", .type=C_ENEMY, .power=4, .copies=1, .set=SET_REAPER},
    {.name="Storm Caller", .type=C_ENEMY, .power=5, .copies=1, .set=SET_REAPER},
    {.name="Miser Dragon", .type=C_ENEMY, .power=7, .copies=1, .set=SET_REAPER},
    {.name="Cave Troll", .type=C_ENEMY, .power=5, .copies=1, .set=SET_REAPER},
    {.name="Cerberus", .type=C_ENEMY, .power=5, .copies=1, .set=SET_REAPER},
    {.name="Chimera", .type=C_ENEMY, .power=5, .copies=1, .set=SET_REAPER},
    {.name="Ekor", .type=C_ENEMY, .power=5, .copies=1, .set=SET_REAPER},
    {.name="Gargoyle", .type=C_ENEMY, .power=3, .copies=1, .set=SET_REAPER},
    {.name="Goblin Trapsmith", .type=C_ENEMY, .power=5, .copies=1, .set=SET_REAPER},
    {.name="Hippogriff", .type=C_ENEMY, .animal=1, .power=3, .copies=1, .set=SET_REAPER},
    {.name="Hydra", .type=C_ENEMY, .power=3, .copies=1, .set=SET_REAPER},
    {.name="Lord of the Pit", .type=C_ENEMY, .power=5, .copies=1, .set=SET_REAPER},
    {.name="Trapper", .type=C_ENEMY, .power=5, .copies=1, .set=SET_REAPER},
    {.name="Banshee", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_REAPER},
    {.name="Black Unicorn", .type=C_SPIRIT, .power=4, .craftfight=1, .copies=1, .set=SET_REAPER},
    {.name="Crone", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_REAPER},
    {.name="Crypt Keeper", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=1, .set=SET_REAPER},
    {.name="Haunt", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_REAPER},
    {.name="Lesser Demon", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=1, .set=SET_REAPER},
    {.name="Mummy", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_REAPER},
    {.name="Nightmare", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_REAPER},
    {.name="Succubus", .type=C_SPIRIT, .power=4, .craftfight=1, .copies=1, .set=SET_REAPER},
    {.name="Astral Conjunction", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_REAPER, .text="it wounds you"},
    {.name="Closed Shop", .type=C_EVENT, .d_craft=1, .copies=1, .set=SET_REAPER, .text="+1 Craft"},
    {.name="Curfew", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_REAPER, .text="+1 Fate"},
    {.name="Earthquake", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_REAPER, .text="it wounds you"},
    {.name="Fool's Gold", .type=C_EVENT, .miss=1, .copies=1, .set=SET_REAPER, .text="you lose your way"},
    {.name="Horse Thief", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_REAPER, .text="+1 Fate"},
    {.name="Patrol", .type=C_EVENT, .d_gold=2, .copies=1, .set=SET_REAPER, .text="+2 Gold"},
    {.name="Prophesy", .type=C_EVENT, .miss=1, .copies=1, .set=SET_REAPER, .text="you lose your way"},
    {.name="The Boatman", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_REAPER, .text="it wounds you"},
    {.name="The Gathering", .type=C_EVENT, .miss=1, .copies=1, .set=SET_REAPER, .text="you lose your way"},
    {.name="Werewolf", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_REAPER, .text="+1 Fate"},
    {.name="Whirlwind", .type=C_EVENT, .miss=1, .copies=1, .set=SET_REAPER, .text="you lose your way"},
    {.name="Colossus", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_REAPER, .text="+1 Strength"},
    {.name="Familiar", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_REAPER, .text="+1 Fate"},
    {.name="Fiend Slayer", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_REAPER, .text="+1 Strength"},
    {.name="Genie", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_REAPER, .text="+1 Strength"},
    {.name="Homunculus", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_REAPER, .text="+1 Fate"},
    {.name="Horse and Cart", .type=C_FOLLOWER, .carry=2, .copies=2, .set=SET_REAPER, .text="carry 2 more Objects"},
    {.name="Jester", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_REAPER, .text="+1 Fate"},
    {.name="Riding Horse", .type=C_FOLLOWER, .carry=2, .copies=2, .set=SET_REAPER, .text="carry 2 more Objects"},
    {.name="St. Josephine", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_REAPER, .text="+1 Fate"},
    {.name="Warhorse", .type=C_FOLLOWER, .carry=2, .copies=1, .set=SET_REAPER, .text="carry 2 more Objects"},
    {.name="Bane Sword", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_REAPER, .text="+1 Strength", .kw=KW_WEAPON},
    {.name="Druid Staff", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_REAPER, .text="+1 Craft"},
    {.name="Elixir of Destiny", .type=C_OBJECT, .d_life=1, .copies=1, .set=SET_REAPER, .text="+1 max Life"},
    {.name="Elixir of Might", .type=C_OBJECT, .d_life=1, .copies=1, .set=SET_REAPER, .text="+1 max Life"},
    {.name="Elixir of Wisdom", .type=C_OBJECT, .d_life=1, .copies=1, .set=SET_REAPER, .text="+1 max Life"},
    {.name="Fate Stealer", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_REAPER, .text="+1 Strength"},
    {.name="Flying Carpet", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_REAPER, .text="+1 Strength"},
    {.name="Hearth Rune", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_REAPER, .text="+1 Craft"},
    {.name="Orb of Destiny", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_REAPER, .text="+1 Craft"},
    {.name="Psychic Crystal", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_REAPER, .text="+1 Craft"},
    {.name="Rod of Ruin", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_REAPER, .text="+1 Strength"},
    {.name="Skull Wand", .type=C_OBJECT, .d_craft=2, .copies=1, .set=SET_REAPER, .text="+2 Craft"},
    {.name="Staff of Mastery", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_REAPER, .text="+1 Craft", .kw=KW_WEAPON},
    {.name="Sword of Light", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_REAPER, .text="+1 Strength", .kw=KW_WEAPON},
    {.name="Talisman", .type=C_OBJECT, .talisman=1, .copies=1, .set=SET_REAPER, .text="opens the Portal of Power"},
    {.name="Armour", .type=C_OBJECT, .copies=1, .set=SET_REAPER, .text="Armour: it may spare you a Life", .kw=KW_ARMOUR},
    {.name="Axe", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_REAPER, .text="+1 Strength", .kw=KW_WEAPON},
    {.name="Casket", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_REAPER, .text="+1 Craft"},
    {.name="Concealed Pouch", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_REAPER, .text="+1 Craft"},
    {.name="Golden Statue", .type=C_GOLD, .d_gold=4, .copies=1, .set=SET_REAPER, .text="Gold"},
    {.name="Map", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_REAPER, .text="+1 Strength"},
    {.name="Shovel", .type=C_OBJECT, .d_life=1, .copies=1, .set=SET_REAPER, .text="+1 max Life"},
    {.name="Two Bags of Gold", .type=C_GOLD, .d_gold=1, .copies=3, .set=SET_REAPER, .text="Gold"},
    {.name="Academy", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_REAPER, .text="stays here: wisdom is offered"},
    {.name="Arena", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_REAPER, .text="stays here: wisdom is offered"},
    {.name="Carnival", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_REAPER, .text="stays here: wisdom is offered"},
    {.name="Idol", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_REAPER, .text="stays here: wisdom is offered"},
    {.name="Pool of Fortune", .type=C_PLACE, .place=PLACE_POOL, .copies=1, .set=SET_REAPER, .text="stays here: it heals"},
    {.name="Tomb", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_REAPER, .text="stays here: wisdom is offered"},
    {.name="Wheel of Fate", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_REAPER, .text="stays here: wisdom is offered"},
    {.name="Demigod", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_REAPER, .text="stays here: wisdom is offered"},
    {.name="Dryad", .type=C_STRANGER, .place=PLACE_FAIRY, .copies=1, .set=SET_REAPER, .text="stays here: Fate is granted"},
    {.name="Leper", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_REAPER, .text="stays here: wisdom is offered"},
    {.name="Magician", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_REAPER, .text="stays here: wisdom is offered"},
    {.name="Outlaw", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_REAPER, .text="stays here: wisdom is offered"},
    {.name="Pathfinder", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_REAPER, .text="stays here: wisdom is offered"},

    /* ---- SET_FROSTMARCH ---- */
    {.name="Ice Bear", .type=C_ENEMY, .animal=1, .power=2, .copies=1, .set=SET_FROSTMARCH},
    {.name="Icecap Elk", .type=C_ENEMY, .animal=1, .power=3, .copies=1, .set=SET_FROSTMARCH},
    {.name="Pack of Wolves", .type=C_ENEMY, .animal=1, .power=4, .copies=1, .set=SET_FROSTMARCH},
    {.name="Winter Wolf", .type=C_ENEMY, .animal=1, .power=3, .copies=1, .set=SET_FROSTMARCH},
    {.name="Cryomancer", .type=C_ENEMY, .power=5, .copies=1, .set=SET_FROSTMARCH},
    {.name="Eastern Dragon", .type=C_ENEMY, .power=7, .copies=1, .set=SET_FROSTMARCH},
    {.name="Frost Drake", .type=C_ENEMY, .power=7, .copies=1, .set=SET_FROSTMARCH},
    {.name="Ice Elemental", .type=C_ENEMY, .power=5, .copies=1, .set=SET_FROSTMARCH},
    {.name="Basilisk", .type=C_ENEMY, .animal=1, .power=3, .copies=1, .set=SET_FROSTMARCH},
    {.name="Frost Giant", .type=C_ENEMY, .power=4, .copies=1, .set=SET_FROSTMARCH},
    {.name="Glory Seeker", .type=C_ENEMY, .power=5, .copies=2, .set=SET_FROSTMARCH},
    {.name="Griffon", .type=C_ENEMY, .animal=1, .power=4, .copies=1, .set=SET_FROSTMARCH},
    {.name="Sky Screecher", .type=C_ENEMY, .power=3, .copies=1, .set=SET_FROSTMARCH},
    {.name="Snow Goblin", .type=C_ENEMY, .power=3, .copies=2, .set=SET_FROSTMARCH},
    {.name="Yeti", .type=C_ENEMY, .animal=1, .power=3, .copies=1, .set=SET_FROSTMARCH},
    {.name="Apparition", .type=C_SPIRIT, .power=4, .craftfight=1, .copies=2, .set=SET_FROSTMARCH},
    {.name="Barrow Wight", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=1, .set=SET_FROSTMARCH},
    {.name="Chill Wraith", .type=C_SPIRIT, .power=4, .craftfight=1, .copies=2, .set=SET_FROSTMARCH},
    {.name="Chillbane", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=1, .set=SET_FROSTMARCH},
    {.name="Lich", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=1, .set=SET_FROSTMARCH},
    {.name="Medusa", .type=C_SPIRIT, .power=4, .craftfight=1, .copies=1, .set=SET_FROSTMARCH},
    {.name="Rimespawn", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=1, .set=SET_FROSTMARCH},
    {.name="Shiver Nymph", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_FROSTMARCH},
    {.name="Trickster", .type=C_SPIRIT, .power=4, .craftfight=1, .copies=1, .set=SET_FROSTMARCH},
    {.name="Divine Protection", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_FROSTMARCH, .text="it wounds you"},
    {.name="Fate Bound", .type=C_EVENT, .miss=1, .copies=1, .set=SET_FROSTMARCH, .text="you lose your way"},
    {.name="Howl of the Wendigo", .type=C_EVENT, .miss=1, .copies=1, .set=SET_FROSTMARCH, .text="you lose your way"},
    {.name="Planeswalker", .type=C_EVENT, .miss=1, .copies=1, .set=SET_FROSTMARCH, .text="you lose your way"},
    {.name="Ragnarok", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Fate"},
    {.name="Snowdrifts", .type=C_EVENT, .miss=1, .copies=1, .set=SET_FROSTMARCH, .text="you wait it out"},
    {.name="Ymir's Glow", .type=C_EVENT, .d_gold=2, .copies=1, .set=SET_FROSTMARCH, .text="+2 Gold"},
    {.name="Champion", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Strength"},
    {.name="Herbalist", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Craft"},
    {.name="Hieromartyr", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Craft"},
    {.name="Porter", .type=C_FOLLOWER, .carry=2, .copies=2, .set=SET_FROSTMARCH, .text="carry 2 more Objects"},
    {.name="Ancient Artefact", .type=C_OBJECT, .d_fate=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Fate"},
    {.name="Bag of Carrying", .type=C_OBJECT, .carry=2, .copies=1, .set=SET_FROSTMARCH, .text="carry 2 more Objects"},
    {.name="Book of Wizardry", .type=C_OBJECT, .d_craft=2, .copies=1, .set=SET_FROSTMARCH, .text="+2 Craft"},
    {.name="Celestial Bauble", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Craft"},
    {.name="Chalice of Shadow", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Strength"},
    {.name="Frostbite", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Strength"},
    {.name="Horn of Summoning", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Craft"},
    {.name="Ice Fang", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Strength", .kw=KW_WEAPON},
    {.name="Winged Boots", .type=C_OBJECT, .d_life=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 max Life"},
    {.name="Astrolabe", .type=C_OBJECT, .d_life=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 max Life"},
    {.name="Bag of Gold", .type=C_GOLD, .d_gold=2, .copies=5, .set=SET_FROSTMARCH, .text="Gold"},
    {.name="False Grail", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Strength"},
    {.name="Helm of Warding", .type=C_OBJECT, .copies=1, .set=SET_FROSTMARCH, .text="Armour: it may spare you a Life", .kw=KW_ARMOUR},
    {.name="Lucky Charm", .type=C_OBJECT, .d_fate=1, .copies=2, .set=SET_FROSTMARCH, .text="+1 Fate"},
    {.name="Mirror Shield", .type=C_OBJECT, .copies=1, .set=SET_FROSTMARCH, .text="Armour: it may spare you a Life", .kw=KW_ARMOUR},
    {.name="Poisoned Dagger", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Strength", .kw=KW_WEAPON},
    {.name="Royal Decree", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_FROSTMARCH, .text="+1 Craft"},
    {.name="Treasure Chest", .type=C_GOLD, .d_gold=1, .copies=2, .set=SET_FROSTMARCH, .text="Gold"},
    {.name="Treasure Map", .type=C_GOLD, .d_gold=4, .copies=2, .set=SET_FROSTMARCH, .text="Gold"},
    {.name="Two Bags of Gold", .type=C_GOLD, .d_gold=1, .copies=2, .set=SET_FROSTMARCH, .text="Gold"},
    {.name="Altar", .type=C_PLACE, .place=PLACE_SHRINE, .copies=1, .set=SET_FROSTMARCH, .text="stays here: it heals"},
    {.name="Arcane Archive", .type=C_PLACE, .place=PLACE_DEN, .copies=2, .set=SET_FROSTMARCH, .text="stays here: it breeds"},
    {.name="Ice Queen's Palace", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FROSTMARCH, .text="stays here: wisdom is offered"},
    {.name="Lake of Visions", .type=C_PLACE, .place=PLACE_POOL, .copies=2, .set=SET_FROSTMARCH, .text="stays here: it heals"},
    {.name="Mystic Portal", .type=C_PLACE, .place=PLACE_PORTAL, .copies=1, .set=SET_FROSTMARCH, .text="stays here: it moves you"},
    {.name="Transmutor", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FROSTMARCH, .text="stays here: wisdom is offered"},
    {.name="Centaur", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FROSTMARCH, .text="stays here: wisdom is offered"},
    {.name="Dwarf Smith", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FROSTMARCH, .text="stays here: wisdom is offered"},
    {.name="Goblin Sapper", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FROSTMARCH, .text="stays here: wisdom is offered"},
    {.name="Lore Master", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FROSTMARCH, .text="stays here: wisdom is offered"},
    {.name="Pedlar", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=2, .set=SET_FROSTMARCH, .text="stays here: wisdom is offered"},
    {.name="Pegasus", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FROSTMARCH, .text="stays here: wisdom is offered"},
    {.name="Talismonger", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FROSTMARCH, .text="stays here: wisdom is offered"},

    /* ---- SET_SACRED ---- */
    {.name="Firemane", .type=C_ENEMY, .power=3, .copies=1, .set=SET_SACRED},
    {.name="Ebony Sentinel", .type=C_ENEMY, .power=5, .copies=1, .set=SET_SACRED},
    {.name="Ivory Sentinel", .type=C_ENEMY, .power=6, .copies=1, .set=SET_SACRED},
    {.name="Vindicator", .type=C_ENEMY, .power=3, .copies=1, .set=SET_SACRED},
    {.name="Wrathborn Acolyte", .type=C_ENEMY, .power=4, .copies=1, .set=SET_SACRED},
    {.name="Wrathborn Knight", .type=C_ENEMY, .power=4, .copies=1, .set=SET_SACRED},
    {.name="Wrathborn Warrior", .type=C_ENEMY, .power=3, .copies=1, .set=SET_SACRED},
    {.name="Wrathborn Witch", .type=C_ENEMY, .power=4, .copies=1, .set=SET_SACRED},
    {.name="Infernal Legion", .type=C_ENEMY, .power=3, .copies=1, .set=SET_SACRED},
    {.name="Pit Fiend", .type=C_ENEMY, .power=4, .copies=1, .set=SET_SACRED},
    {.name="Wretched", .type=C_ENEMY, .power=4, .copies=1, .set=SET_SACRED},
    {.name="Dark Fey", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_SACRED},
    {.name="Fel Steed", .type=C_FOLLOWER, .carry=2, .copies=1, .set=SET_SACRED, .text="carry 2 more Objects"},
    {.name="Heavenly Host", .type=C_SPIRIT, .power=4, .craftfight=1, .copies=1, .set=SET_SACRED},
    {.name="Shadowsoul", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=1, .set=SET_SACRED},
    {.name="Swamp Siren", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=1, .set=SET_SACRED},
    {.name="Angel of Mercy", .type=C_EVENT, .d_life=1, .copies=1, .set=SET_SACRED, .text="+1 Life"},
    {.name="Avatar of Justice", .type=C_EVENT, .d_gold=2, .copies=1, .set=SET_SACRED, .text="+2 Gold"},
    {.name="Discordant Dirge", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_SACRED, .text="+1 Fate"},
    {.name="Equinox", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_SACRED, .text="+1 Fate"},
    {.name="Fallen Angel", .type=C_EVENT, .d_life=1, .copies=1, .set=SET_SACRED, .text="+1 Life"},
    {.name="Fortune's Fool", .type=C_EVENT, .d_gold=2, .copies=1, .set=SET_SACRED, .text="+2 Gold"},
    {.name="Glorious Hymn", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_SACRED, .text="+1 Fate"},
    {.name="Hater Monger", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_SACRED, .text="it wounds you"},
    {.name="Horse Thief", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_SACRED, .text="+1 Fate"},
    {.name="Portent", .type=C_EVENT, .d_gold=2, .copies=2, .set=SET_SACRED, .text="+2 Gold"},
    {.name="Rumour of Riches", .type=C_EVENT, .miss=1, .copies=2, .set=SET_SACRED, .text="you lose your way"},
    {.name="Spiteful Imp", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_SACRED, .text="+1 Fate"},
    {.name="Dark Theurgist", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_SACRED, .text="+1 Strength"},
    {.name="Deathstalker", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_SACRED, .text="+1 Fate"},
    {.name="Defender of Justice", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_SACRED, .text="+1 Strength"},
    {.name="False Prophet", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_SACRED, .text="+1 Craft"},
    {.name="Guardian Angel", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_SACRED, .text="+1 Strength"},
    {.name="Kraven", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_SACRED, .text="+1 Fate"},
    {.name="Mendicant", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_SACRED, .text="+1 Fate"},
    {.name="Oathsworn Guide", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_SACRED, .text="+1 Craft"},
    {.name="Oathsworn Oracle", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_SACRED, .text="+1 Craft"},
    {.name="Theurgist of Light", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_SACRED, .text="+1 Craft"},
    {.name="Baleful Eye", .type=C_OBJECT, .d_fate=1, .copies=1, .set=SET_SACRED, .text="+1 Fate"},
    {.name="Holy Relic", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_SACRED, .text="+1 Craft"},
    {.name="Profane Relic", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_SACRED, .text="+1 Craft"},
    {.name="Shield of Defiance", .type=C_OBJECT, .copies=1, .set=SET_SACRED, .text="Armour: it may spare you a Life", .kw=KW_ARMOUR},
    {.name="Staff of Balance", .type=C_OBJECT, .d_str=2, .copies=1, .set=SET_SACRED, .text="+2 Strength", .kw=KW_WEAPON},
    {.name="Sword of Truth", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_SACRED, .text="+1 Strength", .kw=KW_WEAPON},
    {.name="Wrathborn Wand", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_SACRED, .text="+1 Craft"},
    {.name="Gilded Compass", .type=C_OBJECT, .d_life=1, .copies=1, .set=SET_SACRED, .text="+1 max Life"},
    {.name="Treasure Chest", .type=C_GOLD, .d_gold=1, .copies=2, .set=SET_SACRED, .text="Gold"},
    {.name="Treasure Map", .type=C_GOLD, .d_gold=4, .copies=2, .set=SET_SACRED, .text="Gold"},
    {.name="Cathedral", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Glittering Gorge", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Livery Stable", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=4, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Necropolis", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Pantheon", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=2, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Reliquary", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Augur", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Grace Hearted", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Lawbringer", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Madcap", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=2, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Redeemer", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Renegade", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Ritual Master", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_SACRED, .text="stays here: wisdom is offered"},
    {.name="Warlock's Apprentice", .type=C_STRANGER, .place=PLACE_SPELL, .copies=2, .set=SET_SACRED, .text="stays here: Spells are taught"},

    /* ---- SET_BLOODMOON ---- */
    {.name="Direwolf", .type=C_ENEMY, .power=3, .copies=3, .set=SET_BLOODMOON},
    {.name="Fire Salamander", .type=C_ENEMY, .power=4, .copies=1, .set=SET_BLOODMOON},
    {.name="Flesh Golem", .type=C_ENEMY, .power=4, .copies=1, .set=SET_BLOODMOON},
    {.name="Herald of the Dawn", .type=C_ENEMY, .power=4, .copies=1, .set=SET_BLOODMOON},
    {.name="Scarecrow", .type=C_ENEMY, .power=4, .copies=1, .set=SET_BLOODMOON},
    {.name="Eventide Invoker", .type=C_ENEMY, .power=4, .copies=1, .set=SET_BLOODMOON},
    {.name="Lunar Witch", .type=C_ENEMY, .power=3, .copies=2, .set=SET_BLOODMOON},
    {.name="Night Stalker", .type=C_ENEMY, .power=5, .copies=1, .set=SET_BLOODMOON},
    {.name="Balefire Dragon", .type=C_ENEMY, .power=6, .copies=1, .set=SET_BLOODMOON},
    {.name="Crypt Wyvern", .type=C_ENEMY, .power=8, .copies=1, .set=SET_BLOODMOON},
    {.name="Umblar Drake", .type=C_ENEMY, .power=8, .copies=1, .set=SET_BLOODMOON},
    {.name="Zombie Dragon", .type=C_ENEMY, .power=7, .copies=1, .set=SET_BLOODMOON},
    {.name="Harvest Horror", .type=C_ENEMY, .power=5, .copies=3, .set=SET_BLOODMOON},
    {.name="Crawling Hand", .type=C_ENEMY, .power=3, .copies=2, .set=SET_BLOODMOON},
    {.name="Fire Giant", .type=C_ENEMY, .power=5, .copies=1, .set=SET_BLOODMOON},
    {.name="Lurking Horror", .type=C_ENEMY, .power=3, .copies=1, .set=SET_BLOODMOON},
    {.name="Pit Fiend Shirker", .type=C_ENEMY, .power=4, .copies=1, .set=SET_BLOODMOON},
    {.name="Swamp Creature", .type=C_ENEMY, .power=3, .copies=1, .set=SET_BLOODMOON},
    {.name="Wolfen", .type=C_ENEMY, .power=4, .copies=2, .set=SET_BLOODMOON},
    {.name="Duskwood Wraith", .type=C_SPIRIT, .power=4, .craftfight=1, .copies=2, .set=SET_BLOODMOON},
    {.name="Headless Horseman", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_BLOODMOON},
    {.name="Mummy", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_BLOODMOON},
    {.name="Mummy King", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_BLOODMOON},
    {.name="Night Gaunt", .type=C_SPIRIT, .power=4, .craftfight=1, .copies=1, .set=SET_BLOODMOON},
    {.name="Sepulchre Spectre", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=2, .set=SET_BLOODMOON},
    {.name="Vampire Bats", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_BLOODMOON},
    {.name="Vampire Prince", .type=C_SPIRIT, .power=3, .craftfight=1, .copies=1, .set=SET_BLOODMOON},
    {.name="Growing Suspicions", .type=C_EVENT, .d_craft=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Craft"},
    {.name="Restless Dead", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Black Cat", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Champion of Light", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Strength"},
    {.name="Disciple of Darkness", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Strength"},
    {.name="Fortune Teller", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Keeper of the Vigil", .type=C_FOLLOWER, .d_fate=1, .copies=2, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Lost Soul", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Red Riding Hood", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Craft"},
    {.name="The Bride", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Torchbearer", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Strength"},
    {.name="Witch Finder", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Craft"},
    {.name="Wolf Slayer", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Strength"},
    {.name="Aegis of Daylight", .type=C_EVENT, .d_life=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Life"},
    {.name="All Hallow's Eve", .type=C_EVENT, .d_life=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Life"},
    {.name="Blinding Radiance", .type=C_EVENT, .miss=1, .copies=1, .set=SET_BLOODMOON, .text="you lose your way"},
    {.name="Children of the Night", .type=C_EVENT, .miss=1, .copies=1, .set=SET_BLOODMOON, .text="you lose your way"},
    {.name="Divine Retribution", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Fright Night", .type=C_EVENT, .miss=1, .copies=1, .set=SET_BLOODMOON, .text="you lose your way"},
    {.name="Guiding Light", .type=C_EVENT, .d_life=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Life"},
    {.name="Holy Day", .type=C_EVENT, .d_gold=2, .copies=1, .set=SET_BLOODMOON, .text="+2 Gold"},
    {.name="Luminous Blessing", .type=C_EVENT, .d_life=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Life"},
    {.name="Midnight Howl", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_BLOODMOON, .text="it wounds you"},
    {.name="Moon Mist", .type=C_EVENT, .miss=1, .copies=1, .set=SET_BLOODMOON, .text="you wait it out"},
    {.name="Morning Song", .type=C_EVENT, .d_gold=2, .copies=1, .set=SET_BLOODMOON, .text="+2 Gold"},
    {.name="Night of the Pumpkin King", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Triumphant Daybreak", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Vampiric Thirst", .type=C_EVENT, .d_gold=2, .copies=1, .set=SET_BLOODMOON, .text="+2 Gold"},
    {.name="Witching Hour", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_BLOODMOON, .text="it wounds you"},
    {.name="Doomsword", .type=C_OBJECT, .d_str=2, .copies=1, .set=SET_BLOODMOON, .text="+2 Strength", .kw=KW_WEAPON},
    {.name="Ghostwood Wand", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Craft"},
    {.name="Hammer of Light", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Strength", .kw=KW_WEAPON},
    {.name="Holy Water", .type=C_OBJECT, .d_life=1, .copies=1, .set=SET_BLOODMOON, .text="+1 max Life"},
    {.name="Hungering Artefact", .type=C_OBJECT, .d_fate=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Living Doll", .type=C_OBJECT, .d_fate=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Pharaoh's Crown", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Strength"},
    {.name="Self-Portrait", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Strength"},
    {.name="Shadow Dagger", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Strength", .kw=KW_WEAPON},
    {.name="Sun Shield", .type=C_OBJECT, .copies=1, .set=SET_BLOODMOON, .text="Armour: it may spare you a Life", .kw=KW_ARMOUR},
    {.name="Syphoning Sceptre", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Craft"},
    {.name="Witch's Broom", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Strength"},
    {.name="Book of the Dead", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Craft"},
    {.name="Nightshroud", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Craft"},
    {.name="Prayer Book", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_BLOODMOON, .text="+1 Craft"},
    {.name="Tricks and Treats", .type=C_OBJECT, .d_fate=1, .copies=2, .set=SET_BLOODMOON, .text="+1 Fate"},
    {.name="Wolfsbane", .type=C_OBJECT, .d_life=1, .copies=2, .set=SET_BLOODMOON, .text="+1 max Life"},
    {.name="Wooden Stake", .type=C_OBJECT, .d_str=1, .copies=2, .set=SET_BLOODMOON, .text="+1 Strength"},
    {.name="Boneyard", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="City of Shadows", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Gypsy Caravan", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Haunted Hamlet", .type=C_PLACE, .power=3, .craftfight=1, .place=PLACE_SPIRIT, .copies=1, .set=SET_BLOODMOON, .text="stays here: it haunts"},
    {.name="Laboratory", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Raging Volcano", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Sacred Ground", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Treasure Trove", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=2, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Twilight Forest", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Wall of Fire", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Wolfwood", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Cairn Caretaker", .type=C_STRANGER, .place=PLACE_SHRINE, .copies=1, .set=SET_BLOODMOON, .text="stays here: it heals"},
    {.name="Cauldron Crone", .type=C_STRANGER, .place=PLACE_WITCH, .copies=1, .set=SET_BLOODMOON, .text="stays here: her mood decides"},
    {.name="Corpse Collector", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Dawn Bringer", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Deranged Alchemist", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Fallen Adventurer", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Ghostwood Ent", .type=C_STRANGER, .power=3, .craftfight=1, .place=PLACE_SPIRIT, .copies=1, .set=SET_BLOODMOON, .text="stays here: it haunts"},
    {.name="Lantern Sprite", .type=C_STRANGER, .place=PLACE_FAIRY, .copies=1, .set=SET_BLOODMOON, .text="stays here: Fate is granted"},
    {.name="Mischievous Devil", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Night Carriage", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="Peasant Mob", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_BLOODMOON, .text="stays here: wisdom is offered"},
    {.name="The Phantom", .type=C_STRANGER, .power=4, .craftfight=1, .place=PLACE_SPIRIT, .copies=1, .set=SET_BLOODMOON, .text="stays here: it haunts"},

    /* ---- SET_FIRELANDS ---- */
    {.name="Cultist of Flame", .type=C_ENEMY, .power=3, .copies=1, .set=SET_FIRELANDS},
    {.name="Ifrit Emir", .type=C_ENEMY, .power=6, .copies=1, .set=SET_FIRELANDS},
    {.name="Ifrit Envoy", .type=C_ENEMY, .power=4, .copies=1, .set=SET_FIRELANDS},
    {.name="Ifrit Invader", .type=C_ENEMY, .power=4, .copies=4, .set=SET_FIRELANDS},
    {.name="Ifrit Raider", .type=C_ENEMY, .power=4, .copies=3, .set=SET_FIRELANDS},
    {.name="Ifrit Shapeshifter", .type=C_ENEMY, .power=5, .copies=1, .set=SET_FIRELANDS},
    {.name="Ifrit Sheikh", .type=C_ENEMY, .power=6, .copies=1, .set=SET_FIRELANDS},
    {.name="Ifrit Sorceress", .type=C_ENEMY, .power=4, .copies=1, .set=SET_FIRELANDS},
    {.name="Ifrit Sultan", .type=C_ENEMY, .power=6, .copies=1, .set=SET_FIRELANDS},
    {.name="Ifrit Sultana", .type=C_ENEMY, .power=5, .copies=1, .set=SET_FIRELANDS},
    {.name="City in Flames", .type=C_EVENT, .d_craft=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Craft"},
    {.name="Emerging Volcano", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_FIRELANDS, .text="it wounds you"},
    {.name="Eruption", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_FIRELANDS, .text="it wounds you"},
    {.name="Flame Rift", .type=C_EVENT, .d_fate=1, .copies=5, .set=SET_FIRELANDS, .text="+1 Fate"},
    {.name="Ifrit Hoard", .type=C_EVENT, .d_fate=1, .copies=2, .set=SET_FIRELANDS, .text="+1 Fate"},
    {.name="Ifrit Invasion", .type=C_EVENT, .d_craft=1, .copies=3, .set=SET_FIRELANDS, .text="+1 Craft"},
    {.name="Magma Storm", .type=C_EVENT, .miss=1, .copies=1, .set=SET_FIRELANDS, .text="you wait it out"},
    {.name="Mirage", .type=C_EVENT, .miss=1, .copies=2, .set=SET_FIRELANDS, .text="you lose your way"},
    {.name="Restoring Rains", .type=C_EVENT, .d_fate=1, .copies=2, .set=SET_FIRELANDS, .text="+1 Fate"},
    {.name="Rise of the Phoenix", .type=C_EVENT, .miss=1, .copies=1, .set=SET_FIRELANDS, .text="you lose your way"},
    {.name="Sandstorm", .type=C_EVENT, .miss=1, .copies=1, .set=SET_FIRELANDS, .text="you wait it out"},
    {.name="Temple in Flames", .type=C_EVENT, .d_fate=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Fate"},
    {.name="Bount Ifrit", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Strength"},
    {.name="Camel", .type=C_FOLLOWER, .d_str=1, .copies=2, .set=SET_FIRELANDS, .text="+1 Strength"},
    {.name="Devout Blacksmith", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Craft"},
    {.name="Loyal Vizier", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Craft"},
    {.name="Old Man of the Sea", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Craft"},
    {.name="Royal Masons", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Strength"},
    {.name="Taleweaver", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Strength"},
    {.name="Atlas of Al-Balkhi", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Craft"},
    {.name="Brass Bottle", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Craft"},
    {.name="Enchanted Map", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Strength"},
    {.name="Eternal Talisman", .type=C_OBJECT, .talisman=1, .copies=1, .set=SET_FIRELANDS, .text="opens the Portal of Power", .util=30},
    {.name="Firelands Scourge", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Strength"},
    {.name="Flying Carpet", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Strength"},
    {.name="Inferno Spear", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Strength", .kw=KW_WEAPON},
    {.name="Magic Lamp", .type=C_OBJECT, .d_life=1, .copies=1, .set=SET_FIRELANDS, .text="+1 max Life"},
    {.name="Magic Shovel", .type=C_OBJECT, .d_fate=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Fate"},
    {.name="Orb of Flames", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Craft"},
    {.name="Shamshir of Khamsin", .type=C_OBJECT, .d_life=1, .copies=1, .set=SET_FIRELANDS, .text="+1 max Life"},
    {.name="Suleiman's Seal", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Craft"},
    {.name="Wand of Cinders", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Craft"},
    {.name="Dousing Rod", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Strength"},
    {.name="Ifrit Cloak", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Craft"},
    {.name="Ifrit Gold", .type=C_GOLD, .d_gold=1, .copies=2, .set=SET_FIRELANDS, .text="Gold"},
    {.name="Scimitar", .type=C_OBJECT, .d_str=1, .copies=2, .set=SET_FIRELANDS, .text="+1 Strength", .kw=KW_WEAPON},
    {.name="Seeds of Paradise", .type=C_OBJECT, .d_fate=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Fate"},
    {.name="Simurch Feather", .type=C_OBJECT, .d_str=1, .copies=1, .set=SET_FIRELANDS, .text="+1 Strength"},
    {.name="Taweez Amulet", .type=C_FOLLOWER, .carry=2, .copies=1, .set=SET_FIRELANDS, .text="carry 2 more Objects"},
    {.name="Winter Oil", .type=C_OBJECT, .d_life=1, .copies=1, .set=SET_FIRELANDS, .text="+1 max Life"},
    {.name="Caves of Wonder", .type=C_PLACE, .place=PLACE_DEN, .copies=1, .set=SET_FIRELANDS, .text="stays here: it breeds"},
    {.name="City of the Ifrit", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FIRELANDS, .text="stays here: wisdom is offered"},
    {.name="House of Wisdom", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FIRELANDS, .text="stays here: wisdom is offered"},
    {.name="Lava Pools", .type=C_PLACE, .place=PLACE_POOL, .copies=1, .set=SET_FIRELANDS, .text="stays here: it heals"},
    {.name="Sacrificial Alter", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FIRELANDS, .text="stays here: wisdom is offered"},
    {.name="The Grand Bazaar", .type=C_PLACE, .place=PLACE_SHOP, .copies=1, .set=SET_FIRELANDS, .text="stays here: a market"},
    {.name="Wasteland", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FIRELANDS, .text="stays here: wisdom is offered"},
    {.name="Bass Horseman", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FIRELANDS, .text="stays here: wisdom is offered"},
    {.name="Djinn Sultan", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FIRELANDS, .text="stays here: wisdom is offered"},
    {.name="Harbinger of Flame", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FIRELANDS, .text="stays here: wisdom is offered"},
    {.name="Leper", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FIRELANDS, .text="stays here: wisdom is offered"},
    {.name="Marid Sultana", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FIRELANDS, .text="stays here: wisdom is offered"},
    {.name="Nefarious Vizier", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FIRELANDS, .text="stays here: wisdom is offered"},
    {.name="Questing Prince", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_FIRELANDS, .text="stays here: wisdom is offered"},

    /* ---- SET_CATACLYSM ---- */
    {.name="Junk Golem", .type=C_ENEMY, .power=6, .copies=1, .set=SET_CATACLYSM},
    {.name="Blightwood Rabble", .type=C_ENEMY, .power=3, .copies=1, .set=SET_CATACLYSM},
    {.name="Blightwood Slaver", .type=C_ENEMY, .power=4, .copies=2, .set=SET_CATACLYSM},
    {.name="Aeon Demon", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_CATACLYSM},
    {.name="Void Demon", .type=C_SPIRIT, .power=5, .craftfight=1, .copies=1, .set=SET_CATACLYSM},
    {.name="Ironscale Dragon", .type=C_ENEMY, .power=6, .copies=1, .set=SET_CATACLYSM},
    {.name="Mongrel Sprite", .type=C_ENEMY, .power=3, .copies=1, .set=SET_CATACLYSM},
    {.name="Blightwood Terror", .type=C_ENEMY, .power=3, .copies=1, .set=SET_CATACLYSM},
    {.name="Ashfield Looters", .type=C_ENEMY, .power=3, .copies=2, .set=SET_CATACLYSM},
    {.name="Queen of Ashes", .type=C_ENEMY, .power=4, .copies=1, .set=SET_CATACLYSM},
    {.name="Rusthill Marauders", .type=C_ENEMY, .power=4, .copies=2, .set=SET_CATACLYSM},
    {.name="Abomination Wraith", .type=C_SPIRIT, .power=4, .craftfight=1, .copies=1, .set=SET_CATACLYSM},
    {.name="Ancient Lich", .type=C_ENEMY, .power=6, .copies=1, .set=SET_CATACLYSM},
    {.name="Undying Horde", .type=C_ENEMY, .power=6, .copies=1, .set=SET_CATACLYSM},
    {.name="Apocalypse Storm", .type=C_EVENT, .miss=1, .copies=1, .set=SET_CATACLYSM, .text="you wait it out"},
    {.name="Chance Meeting", .type=C_EVENT, .d_gold=2, .copies=2, .set=SET_CATACLYSM, .text="+2 Gold"},
    {.name="Dead Magic", .type=C_EVENT, .d_gold=2, .copies=2, .set=SET_CATACLYSM, .text="+2 Gold"},
    {.name="Divine Blessings", .type=C_EVENT, .d_life=1, .copies=1, .set=SET_CATACLYSM, .text="+1 Life"},
    {.name="Market Day", .type=C_EVENT, .d_gold=2, .copies=1, .set=SET_CATACLYSM, .text="+2 Gold"},
    {.name="Rebirth", .type=C_EVENT, .d_life=-1, .copies=1, .set=SET_CATACLYSM, .text="it wounds you"},
    {.name="Rebuilding", .type=C_EVENT, .miss=1, .copies=1, .set=SET_CATACLYSM, .text="you lose your way"},
    {.name="Scavenging", .type=C_EVENT, .d_fate=1, .copies=2, .set=SET_CATACLYSM, .text="+1 Fate"},
    {.name="Barrowtown Hunter", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_CATACLYSM, .text="+1 Strength"},
    {.name="Brakwater Diver", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_CATACLYSM, .text="+1 Fate"},
    {.name="Deadlands Survivor", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_CATACLYSM, .text="+1 Craft"},
    {.name="Havenville Recruiter", .type=C_FOLLOWER, .d_craft=1, .copies=1, .set=SET_CATACLYSM, .text="+1 Craft"},
    {.name="Rotsnout Dog", .type=C_FOLLOWER, .d_str=1, .copies=1, .set=SET_CATACLYSM, .text="+1 Strength"},
    {.name="Trashtown Thief", .type=C_FOLLOWER, .d_fate=1, .copies=1, .set=SET_CATACLYSM, .text="+1 Fate"},
    {.name="Broken Relic", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_CATACLYSM, .text="+1 Craft"},
    {.name="Personal Invitation", .type=C_OBJECT, .d_craft=1, .copies=1, .set=SET_CATACLYSM, .text="+1 Craft"},
    {.name="Ashfield Hideout", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_CATACLYSM, .text="stays here: wisdom is offered"},
    {.name="Astral Rift", .type=C_PLACE, .place=PLACE_PORTAL, .copies=1, .set=SET_CATACLYSM, .text="stays here: it moves you"},
    {.name="Blightwood Shrine", .type=C_PLACE, .place=PLACE_SHRINE, .copies=1, .set=SET_CATACLYSM, .text="stays here: it heals"},
    {.name="Havenville", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_CATACLYSM, .text="stays here: wisdom is offered"},
    {.name="Meeting Place", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_CATACLYSM, .text="stays here: wisdom is offered"},
    {.name="Trashtown", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_CATACLYSM, .text="stays here: wisdom is offered"},
    {.name="Astral Spirit", .type=C_STRANGER, .power=3, .craftfight=1, .place=PLACE_SPIRIT, .copies=1, .set=SET_CATACLYSM, .text="stays here: it haunts"},
    {.name="Brakwater Traders", .type=C_STRANGER, .place=PLACE_SHOP, .copies=1, .set=SET_CATACLYSM, .text="stays here: a market"},
    {.name="Fugitive Demon", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_CATACLYSM, .text="stays here: wisdom is offered"},
    {.name="Junk Dealer", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_CATACLYSM, .text="stays here: wisdom is offered"},
    {.name="Order of Josephine", .type=C_STRANGER, .place=PLACE_FOUNTAIN, .copies=1, .set=SET_CATACLYSM, .text="stays here: wisdom is offered"},

    /* ---- SET_DUNGEON ---- */
    {.name="Burrow Worm", .type=C_ENEMY, .power=3, .copies=1, .set=SET_DUNGEON},
    {.name="Dark Denizens", .type=C_EVENT, .d_life=-1, .copies=2, .set=SET_DUNGEON, .text="it wounds you"},
    {.name="Trap Door", .type=C_EVENT, .miss=1, .copies=2, .set=SET_DUNGEON, .text="you lose your way"},
    {.name="Dungeon Door", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=2, .set=SET_DUNGEON, .text="stays here: wisdom is offered"},
    {.name="Rune Gate", .type=C_PLACE, .place=PLACE_PORTAL, .copies=3, .set=SET_DUNGEON, .text="stays here: it moves you"},

    /* ---- SET_HIGHLAND ---- */
    {.name="Roc", .type=C_ENEMY, .power=3, .copies=2, .set=SET_HIGHLAND},
    {.name="Earth Elemental", .type=C_ENEMY, .power=4, .copies=1, .set=SET_HIGHLAND},
    {.name="Eyrie Vanguard", .type=C_EVENT, .d_gold=2, .copies=2, .set=SET_HIGHLAND, .text="+2 Gold"},
    {.name="Landslide", .type=C_EVENT, .d_gold=2, .copies=2, .set=SET_HIGHLAND, .text="+2 Gold"},
    {.name="Magic Gateway", .type=C_EVENT, .d_gold=2, .copies=1, .set=SET_HIGHLAND, .text="+2 Gold"},
    {.name="Mountain Trail", .type=C_PLACE, .place=PLACE_FOUNTAIN, .copies=2, .set=SET_HIGHLAND, .text="stays here: wisdom is offered"},
    {.name="Rune Gate", .type=C_PLACE, .place=PLACE_PORTAL, .copies=2, .set=SET_HIGHLAND, .text="stays here: it moves you"},

    /* ---- SET_WOODLAND ---- */
    {.name="Faerie Host", .type=C_EVENT, .miss=1, .copies=2, .set=SET_WOODLAND, .text="you lose your way"},
    {.name="Faerie Trod", .type=C_EVENT, .miss=1, .copies=2, .set=SET_WOODLAND, .text="you lose your way"},
    {.name="Master of Fate", .type=C_EVENT, .d_gold=2, .copies=2, .set=SET_WOODLAND, .text="+2 Gold"},
    {.name="Faerie Gate", .type=C_PLACE, .place=PLACE_PORTAL, .copies=2, .set=SET_WOODLAND, .text="stays here: it moves you"},
    {.name="Faerie Glade", .type=C_PLACE, .place=PLACE_FAIRY, .copies=2, .set=SET_WOODLAND, .text="stays here: Fate is granted"},
    /* --- the City's own Adventure deck (OCR'd; see CARDS-city-time.tsv) --- */
    {.name="Conscription", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="Cutpurse", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="Drunken Revelry", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="Employment", .type=C_EVENT, .copies=2, .set=SET_CITYD},
    {.name="Festival", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="Gambler", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="Heretic Priest", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="Horse Thief", .type=C_EVENT, .copies=2, .set=SET_CITYD},
    {.name="Lost", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="Market Day", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="Master Thief Strength", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="Plague", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="War", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="Corrupt Sheriff", .type=C_EVENT, .power=6, .copies=1, .set=SET_CITYD},
    {.name="Honest Deputy", .type=C_EVENT, .power=7, .copies=1, .set=SET_CITYD},
    {.name="The Watch", .type=C_EVENT, .power=4, .copies=7, .set=SET_CITYD},
    {.name="The Watch Strength", .type=C_EVENT, .copies=1, .set=SET_CITYD},
    {.name="Baker", .type=C_STRANGER, .copies=1, .set=SET_CITYD},
    {.name="Barterer", .type=C_STRANGER, .copies=1, .set=SET_CITYD},
    {.name="Beggar", .type=C_STRANGER, .copies=3, .set=SET_CITYD},
    {.name="Butcher", .type=C_STRANGER, .copies=1, .set=SET_CITYD},
    {.name="Grifter", .type=C_STRANGER, .copies=1, .set=SET_CITYD},
    {.name="Grumpy Wizard", .type=C_STRANGER, .copies=1, .set=SET_CITYD},
    {.name="Salesman", .type=C_STRANGER, .copies=1, .set=SET_CITYD},
    {.name="Street Sage", .type=C_STRANGER, .copies=1, .set=SET_CITYD},
    {.name="Bag", .type=C_OBJECT, .copies=4, .set=SET_CITYD, .text="exchange it for a Bag of Gold", .d_gold=2},
    {.name="Broken Helmet", .type=C_OBJECT, .copies=1, .set=SET_CITYD, .text="mendable at the City Armoury for 1 Gold", .util=3},
    {.name="Damaged Armour", .type=C_OBJECT, .copies=1, .set=SET_CITYD, .text="mendable at the City Armoury for 1 Gold", .util=3},
    {.name="Dog", .type=C_FOLLOWER, .power=2, .copies=1, .set=SET_CITYD},
    {.name="Gamekeeper", .type=C_FOLLOWER, .copies=1, .set=SET_CITYD},
    {.name="Money Belt", .type=C_OBJECT, .copies=1, .set=SET_CITYD, .text="your Gold cannot be stolen", .util=3},
    /* --- the Timescape deck --- */
    {.name="Dimensional Rift", .type=C_EVENT, .copies=4, .set=SET_TIMED},
    {.name="Orks", .type=C_EVENT, .power=4, .copies=1, .set=SET_TIMED},
    {.name="Supernova", .type=C_EVENT, .copies=4, .set=SET_TIMED},
    {.name="Warp Storm", .type=C_EVENT, .copies=1, .set=SET_TIMED},
    {.name="Omnipotent Being", .type=C_STRANGER, .copies=1, .set=SET_TIMED},
    {.name="Time Travellers", .type=C_STRANGER, .copies=1, .set=SET_TIMED},
    {.name="Alien Artifact", .type=C_OBJECT, .copies=3, .set=SET_TIMED, .text="trade it for 2 Gold", .d_gold=2},
    {.name="Alien Artifact Pls", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="trade it for 2 Gold", .d_gold=2},
    {.name="Anti-grav Platform", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="carry 4 more Objects", .carry=4},
    {.name="Battle Armour", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="+1 Strength; it may spare you a Life", .d_str=1, .kw=KW_ARMOUR},
    {.name="Battle Droid", .type=C_FOLLOWER, .power=6, .copies=1, .set=SET_TIMED},
    {.name="Chameleon Suit", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="a fair chance to slip away unseen", .util=4},
    {.name="Combat Enviro-suit", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="safe in the Rad Zone", .util=4},
    {.name="Force Shield", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="a lost Life may be turned aside", .kw=KW_ARMOUR},
    {.name="Gyro-compass", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="+2 Craft in the Timescape", .util=4},
    {.name="Jet Pack", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="adds to your Movement roll", .util=5},
    {.name="Medi-kit", .type=C_OBJECT, .copies=2, .set=SET_TIMED, .text="heals up to 2 Lives, once", .util=8},
    {.name="Mining Laser", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="+2 Strength", .d_str=2, .kw=KW_WEAPON},
    {.name="Power Glove", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="+2 Strength in Combat", .d_str=2, .kw=KW_WEAPON},
    {.name="Psi-helmet", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="+2 Craft in Psychic Combat", .d_craft=2},
    {.name="Warp-belt", .type=C_OBJECT, .copies=1, .set=SET_TIMED, .text="move one space of your choice instead of rolling", .util=5},
    {.name="Star Sprites", .type=C_FOLLOWER, .copies=1, .set=SET_TIMED},
    {.name="Symbiote", .type=C_FOLLOWER, .copies=1, .set=SET_TIMED},
    {.name=NULL}
};

/* The 24-card Spell deck of the base game, with its real copy counts. */
const Spell spell_proto[] = {
    {"Acquisition",   SK_ACQUIRE,      1, SET_BASE, "take an Object from a character here"},
    {"Alchemy", SK_ALCHEMY, 1, SET_BASE, "turn one of your Objects into 3 Gold"},
    {"Counterspell", SK_COUNTER, 2, SET_BASE, "a rival must discard a Spell"},
    {"Destroy Magic", SK_DESTROYMAGIC, 1, SET_BASE, "wipe a Place or Stranger from this space"},
    {"Destruction", SK_DESTRUCTION, 2, SET_BASE, "destroy a creature standing on this space"},
    {"Divination", SK_DIVINATION, 1, SET_BASE, "read the future: +1 Fate"},
    {"Healing", SK_HEAL, 2, SET_BASE, "heal 1 Life"},
    {"Hex", SK_HEX, 1, SET_BASE, "a rival in your Region loses 1 Life"},
    {"Immobility", SK_IMMOBILITY, 2, SET_BASE, "a rival misses their next turn"},
    {"Invisibility", SK_INVISIBLE, 1, SET_BASE, "slip away: no battle at all"},
    {"Mesmerism", SK_MESMERISE, 1, SET_BASE, "take a Follower from a character here"},
    {"Nullify", SK_NULLIFY, 1, SET_BASE, "force the creature to roll again"},
    {"Preservation", SK_PRESERVE, 1, SET_BASE, "the next Life you would lose is spared"},
    {"Psionic Blast", SK_PSIONIC, 2, SET_BASE, "add your Craft to your Strength"},
    {"Random", SK_RANDOM, 2, SET_BASE, "the dice decide your fortune"},
    {"Teleport", SK_TELEPORT, 2, SET_BASE, "move to any space on your ring"},
    {"Temporal Warp", SK_WARP, 1, SET_BASE, "take another turn at once"},
    /* ---- SET_REAPER ---- */
    {"Alteration", SK_RANDOM, 1, SET_REAPER, "the dice decide your fortune"},
    {"Barrier", SK_HEX, 1, SET_REAPER, "a rival in your Region loses 1 Life"},
    {"Bladesharp", SK_HEX, 1, SET_REAPER, "a rival in your Region loses 1 Life"},
    {"Blessed", SK_IMMOBILITY, 1, SET_REAPER, "a rival misses their next turn"},
    {"Cloak of Shadows", SK_PSIONIC, 1, SET_REAPER, "add your Craft to your Strength"},
    {"Displacement", SK_HEAL, 2, SET_REAPER, "heal 1 Life"},
    {"Displacement", SK_HEAL, 1, SET_REAPER, "heal 1 Life"},
    {"Dominate", SK_MESMERISE, 1, SET_REAPER, "take a Follower from a character here"},
    {"Enchant Blade", SK_PRESERVE, 1, SET_REAPER, "the next Life you would lose is spared"},
    {"Enrich", SK_HEX, 1, SET_REAPER, "a rival in your Region loses 1 Life"},
    {"Fireball", SK_HEAL, 1, SET_REAPER, "heal 1 Life"},
    {"Gust of Wind", SK_IMMOBILITY, 1, SET_REAPER, "a rival misses their next turn"},
    {"Misdirection", SK_DIVINATION, 1, SET_REAPER, "read the future: +1 Fate"},
    {"Reflection", SK_HEAL, 1, SET_REAPER, "heal 1 Life"},
    {"Resurrection", SK_PRESERVE, 1, SET_REAPER, "the next Life you would lose is spared"},
    {"Shatter", SK_DESTRUCTION, 1, SET_REAPER, "destroy a creature on this space"},
    {"Sleep", SK_HEX, 1, SET_REAPER, "a rival in your Region loses 1 Life"},
    {"Slow Motion", SK_IMMOBILITY, 1, SET_REAPER, "a rival misses their next turn"},
    {"Speed", SK_PRESERVE, 1, SET_REAPER, "the next Life you would lose is spared"},
    {"Summon Bear", SK_PRESERVE, 1, SET_REAPER, "the next Life you would lose is spared"},
    {"Summon Phoenix", SK_PRESERVE, 1, SET_REAPER, "the next Life you would lose is spared"},
    {"Summon Serpent", SK_PSIONIC, 1, SET_REAPER, "add your Craft to your Strength"},
    {"Summon Stormcrow", SK_RANDOM, 1, SET_REAPER, "the dice decide your fortune"},
    {"Transference", SK_DIVINATION, 1, SET_REAPER, "read the future: +1 Fate"},
    {"Transmute", SK_ALCHEMY, 1, SET_REAPER, "turn one of your Objects into 3 Gold"},
    {"Water Walking", SK_HEAL, 1, SET_REAPER, "heal 1 Life"},

    /* ---- SET_FROSTMARCH ---- */
    {"Black Ice", SK_HEAL, 1, SET_FROSTMARCH, "heal 1 Life"},
    {"Bolster", SK_PSIONIC, 2, SET_FROSTMARCH, "add your Craft to your Strength"},
    {"Brainwave", SK_PRESERVE, 2, SET_FROSTMARCH, "the next Life you would lose is spared"},
    {"Energize", SK_PRESERVE, 2, SET_FROSTMARCH, "the next Life you would lose is spared"},
    {"Freeze", SK_IMMOBILITY, 1, SET_FROSTMARCH, "a rival misses their next turn"},
    {"Hydra Spell", SK_HEAL, 1, SET_FROSTMARCH, "heal 1 Life"},
    {"Marked for Glory", SK_DIVINATION, 1, SET_FROSTMARCH, "read the future: +1 Fate"},
    {"Metamorph", SK_PRESERVE, 1, SET_FROSTMARCH, "the next Life you would lose is spared"},
    {"Obliterate", SK_DIVINATION, 1, SET_FROSTMARCH, "read the future: +1 Fate"},
    {"Path of Destiny", SK_PSIONIC, 2, SET_FROSTMARCH, "add your Craft to your Strength"},
    {"Syphon Strength", SK_IMMOBILITY, 1, SET_FROSTMARCH, "a rival misses their next turn"},
    {"Time Steal", SK_ACQUIRE, 2, SET_FROSTMARCH, "take an Object from a character here"},
    {"Toadify!", SK_TOAD, 2, SET_FROSTMARCH, "a toad for three Turns, and drops all they carry"},
    {"Vortex", SK_HEX, 1, SET_FROSTMARCH, "a rival in your Region loses 1 Life"},

    /* ---- SET_SACRED ---- */
    {"Cheat Fate", SK_PRESERVE, 1, SET_SACRED, "the next Life you would lose is spared"},
    {"Feeble Mind", SK_PSIONIC, 1, SET_SACRED, "add your Craft to your Strength"},
    {"Generosity", SK_IMMOBILITY, 1, SET_SACRED, "a rival misses their next turn"},
    {"Invoke Favour", SK_DIVINATION, 2, SET_SACRED, "read the future: +1 Fate"},
    {"Life Tap", SK_IMMOBILITY, 1, SET_SACRED, "a rival misses their next turn"},
    {"Mini-Vortex", SK_HEX, 1, SET_SACRED, "a rival in your Region loses 1 Life"},
    {"Misfortune", SK_RANDOM, 2, SET_SACRED, "the dice decide your fortune"},
    {"Retribution", SK_PSIONIC, 1, SET_SACRED, "add your Craft to your Strength"},
    {"Reverence", SK_HEX, 1, SET_SACRED, "a rival in your Region loses 1 Life"},
    {"Stasis", SK_HEAL, 2, SET_SACRED, "heal 1 Life"},
    {"Temporary Change", SK_PSIONIC, 2, SET_SACRED, "add your Craft to your Strength"},
    {"Vindication", SK_HEAL, 1, SET_SACRED, "heal 1 Life"},

    /* ---- SET_BLOODMOON ---- */
    {"Haunting Poltergeist", SK_HEX, 1, SET_BLOODMOON, "a rival in your Region loses 1 Life"},
    {"Benediction", SK_RANDOM, 1, SET_BLOODMOON, "the dice decide your fortune"},
    {"Burial Rites", SK_RANDOM, 1, SET_BLOODMOON, "the dice decide your fortune"},
    {"Curse of the Werewolf", SK_HEX, 2, SET_BLOODMOON, "a rival in your Region loses 1 Life"},
    {"Drain Life", SK_IMMOBILITY, 1, SET_BLOODMOON, "a rival misses their next turn"},
    {"Exorcise", SK_PRESERVE, 1, SET_BLOODMOON, "the next Life you would lose is spared"},
    {"Feral Hunger", SK_DIVINATION, 1, SET_BLOODMOON, "read the future: +1 Fate"},
    {"Reanimate", SK_HEX, 1, SET_BLOODMOON, "a rival in your Region loses 1 Life"},
    {"Solstice Ritual", SK_RANDOM, 1, SET_BLOODMOON, "the dice decide your fortune"},

    /* ---- SET_FIRELANDS ---- */
    {"Burning Curiosity", SK_IMMOBILITY, 1, SET_FIRELANDS, "a rival misses their next turn"},
    {"Conflagration", SK_RANDOM, 1, SET_FIRELANDS, "the dice decide your fortune"},
    {"Crack the Earth", SK_RANDOM, 2, SET_FIRELANDS, "the dice decide your fortune"},
    {"Curse of Flame", SK_HEX, 1, SET_FIRELANDS, "a rival in your Region loses 1 Life"},
    {"Desolation", SK_PRESERVE, 1, SET_FIRELANDS, "the next Life you would lose is spared"},
    {"Disguise", SK_DIVINATION, 1, SET_FIRELANDS, "read the future: +1 Fate"},
    {"Evil Eye", SK_PSIONIC, 1, SET_FIRELANDS, "add your Craft to your Strength"},
    {"Extinguish", SK_PSIONIC, 2, SET_FIRELANDS, "add your Craft to your Strength"},
    {"Fiery Retribution", SK_RANDOM, 1, SET_FIRELANDS, "the dice decide your fortune"},
    {"Restore the World", SK_HEAL, 2, SET_FIRELANDS, "heal 1 Life"},
    {"Spell Scorch", SK_IMMOBILITY, 1, SET_FIRELANDS, "a rival misses their next turn"},
    {"Suleiman's Command", SK_MESMERISE, 1, SET_FIRELANDS, "take a Follower from a character here"},
    {"Terramorph", SK_DIVINATION, 2, SET_FIRELANDS, "read the future: +1 Fate"},
    {"Upheaval", SK_PSIONIC, 1, SET_FIRELANDS, "add your Craft to your Strength"},
    {"Verdant Growth", SK_HEX, 1, SET_FIRELANDS, "a rival in your Region loses 1 Life"},

    /* ---- SET_CATACLYSM ---- */
    {"Arcane Construction", SK_IMMOBILITY, 1, SET_CATACLYSM, "a rival misses their next turn"},
    {"Astral Journey", SK_TELEPORT, 1, SET_CATACLYSM, "move to the crossing on your ring"},
    {"Blink", SK_PSIONIC, 2, SET_CATACLYSM, "add your Craft to your Strength"},
    {"Curse of Rust", SK_HEX, 1, SET_CATACLYSM, "a rival in your Region loses 1 Life"},
    {"Death Pact", SK_RANDOM, 1, SET_CATACLYSM, "the dice decide your fortune"},
    {"Miser's Grasp", SK_ACQUIRE, 1, SET_CATACLYSM, "take an Object from a character here"},
    {"Mutation", SK_PSIONIC, 2, SET_CATACLYSM, "add your Craft to your Strength"},
    {"Reclamation", SK_HEAL, 1, SET_CATACLYSM, "heal 1 Life"},

    /* ---- SET_DUNGEON ---- */
    {"Craft", SK_HEAL, 2, SET_DUNGEON, "heal 1 Life"},
    {"Divine Intervention", SK_DIVINATION, 2, SET_DUNGEON, "read the future: +1 Fate"},
    {"Finger of Death", SK_HEAL, 1, SET_DUNGEON, "heal 1 Life"},
    {"Magic Portal", SK_RANDOM, 2, SET_DUNGEON, "the dice decide your fortune"},
    {"Magic Shell", SK_RANDOM, 1, SET_DUNGEON, "the dice decide your fortune"},
    {"Restoration", SK_HEAL, 2, SET_DUNGEON, "heal 1 Life"},
    {"Spell Call", SK_HEX, 2, SET_DUNGEON, "a rival in your Region loses 1 Life"},
    {"Strength", SK_PRESERVE, 2, SET_DUNGEON, "the next Life you would lose is spared"},
    {"Summon Storm", SK_HEX, 1, SET_DUNGEON, "a rival in your Region loses 1 Life"},
    {"Temporal Vortex", SK_WARP, 1, SET_DUNGEON, "take another turn at once"},
    {"Twist of Fate", SK_HEX, 2, SET_DUNGEON, "a rival in your Region loses 1 Life"},
    {"Weakness", SK_PSIONIC, 2, SET_DUNGEON, "add your Craft to your Strength"},

    /* ---- SET_HIGHLAND ---- */
    {"Eyes of the Hawk", SK_IMMOBILITY, 2, SET_HIGHLAND, "a rival misses their next turn"},
    {"Lightning Bolt", SK_RANDOM, 2, SET_HIGHLAND, "the dice decide your fortune"},
    {"Mind Steal", SK_PSIONIC, 2, SET_HIGHLAND, "add your Craft to your Strength"},
    {"Simulacrum", SK_IMMOBILITY, 2, SET_HIGHLAND, "a rival misses their next turn"},
    {"Soul Shatter", SK_DESTRUCTION, 2, SET_HIGHLAND, "destroy a creature on this space"},

    /* ---- SET_WOODLAND ---- */
    {"Cut the Thread", SK_IMMOBILITY, 3, SET_WOODLAND, "a rival misses their next turn"},
    {"Forge Destiny", SK_PRESERVE, 1, SET_WOODLAND, "the next Life you would lose is spared"},
    {"Rejuvenation", SK_RANDOM, 1, SET_WOODLAND, "the dice decide your fortune"},

    /* ---- SET_HARBINGER ---- */
    {"Augury", SK_DIVINATION, 2, SET_HARBINGER, "read the future: +1 Fate"},
    {"Dark Binding", SK_IMMOBILITY, 2, SET_HARBINGER, "a rival misses their next turn"},
    {"Dispellation", SK_COUNTER, 2, SET_HARBINGER, "a rival must discard a Spell"},
    {"Sacred Offering", SK_DIVINATION, 2, SET_HARBINGER, "read the future: +1 Fate"},
    {"Terra Shift", SK_TELEPORT, 2, SET_HARBINGER, "move to the crossing on your ring"},
    {NULL, SK_HEAL, 0, SET_BASE, NULL}
};

/* Prices are ours -- the card list carries none.  Counts are the real ones. */
const Wares purchase_proto[] = {
    {"Sword",        2, 3},
    {"Axe",          2, 4},
    {"Shield",       2, 4},
    {"Helmet",       2, 4},
    {"Armour",       3, 4},
    {"Water Bottle", 1, 4},
    {"Raft",         1, 1},
    {"Mule",         6, 4},
    {NULL, 0, 0}
};
